### ISSUE TITLE
Please include social login examples also

### ISSUE THREAD

**Issue by yashg5** [AnomalyInnovations/serverless-stack-com#110]
Facebook and google login and how to store them in user pool. it would be lot helpful. I am not able to find good examples anywhere to work on. If you have any external examples for the same please provide

**Comment by jayair** [comment]
@yashg5 With the current set up we have, it is a little tricky to add Facebook and Google. The new update that we are making to the tutorial will make this easier to do. Stay tuned! - https://github.com/AnomalyInnovations/serverless-stack-com/issues/108

**Comment by sanjosedennis7593** [comment]
Hi,

I already did the facebook login, i just want to asked, how to handle session using facebook login? What i mean is that when i refreshed the page, it will maintain the session state of the current user.

**Comment by jayair** [comment]
@sanjosedennis7593 Are you using the FB SDK?

**Comment by sanjosedennis7593** [comment]
Yes, i'm using FB SDK, once i logged in, i get the credentials using the AWS.config.credentials, unfortunately, when i tried to refresh the page, it clears the value in the AWS.config.credentials object.

**Comment by jayair** [comment]
This is true even for our current tutorial. We call `authUser` every time the page is refreshed - https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/src/App.js#L21.

I think you'll need to do the same for FB. Check if the user is logged in using FB when the page loads and get a set of temporary credentials.

**Comment by jatazoulja** [comment]
@sanjosedennis7593 can you share your code? I am also block by `AWS.config.credentials.getPromise()` not waiting to resolve or alway undefined (not async)
in any case could this help:
https://github.com/aws/aws-sdk-js/issues/1097

please share if your successful...
