### ISSUE TITLE
Reset libs cache

### ISSUE THREAD

**Issue by ebisbe** [AnomalyInnovations/serverless-stack-com#119]
I've found that the files under libs/ folder are cached. How can we refresh it if we made some changes to those files?

**Comment by jayair** [comment]
Are we talking about the frontend or the backend?

**Comment by ebisbe** [comment]
sorry @jayair , in the back end. The ones that work with serverless. In the output while deploying it doesn't says [not cacheable] so I assume they are cached and there for my change in the file under libs/ doesn't gets updated in  the lambda function.
I've tried to remove and deploy to see if it was an issue with aws but it don't seems to me.

**Comment by ebisbe** [comment]
I think it's something related with aws lambda panel because now it's working.
