### ISSUE TITLE
Constraint Error when verifying account using administrator command

### ISSUE THREAD

**Issue by vaughanhale** [AnomalyInnovations/serverless-stack-com#127]
When I run the below command (with my UserPoolId and the email I used to create the user)
```
aws cognito-idp admin-confirm-sign-up \
  --region us-east-1 \
  --user-pool-id YOUR_USER_POOL_ID \
  --username admin@example.com
```
I get the below error message..
An error occurred (InvalidParameterException) when calling the AdminConfirmSignUp operation: 1 validation error detected: Value 'YOUR_USER_POOL_ID' at 'userPoolId' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w-]+_[0-9a-zA-Z]+

I thought it might have been that the password was to simple, however I used "Passw0rd!" which seems to satisfy the password policy:

Minimum length: 8
Require numbers
Require special character
Require uppercase letters
Require lowercase letters

**Comment by QuantumInformation** [comment]
What was your solution?

**Comment by QuantumInformation** [comment]
If you created the user then the password must already have been accepted. 

I have the same error ATM.

**Comment by vaughanhale** [comment]
I was using the wrong value for userPoolId.

**Comment by jayair** [comment]
@QuantumInformation I'm not sure if you noticed this, but the userPoolId is not the user id of the user. But the ID of the User Pool itself.

**Comment by kpahi** [comment]
saved my day.
Thanks

**Comment by agam-mishra** [comment]
I got the same error.

Solution was simple.
1. Go to your Cognito console and look for **Pool Id**, copy it and paste it in your terminal in place of YOUR_COGNITO_USER_POOL_ID.
