### ISSUE TITLE
Would it be useful to have Gitter/Discord/Slack room for this book?

### ISSUE THREAD

**Issue by QuantumInformation** [AnomalyInnovations/serverless-stack-com#132]

**Comment by bharloe** [comment]
Yes

**Comment by jayair** [comment]
Yeah we have gotten a few requests for this. We'll be creating one soon!

**Comment by QuantumInformation** [comment]
Its tricky cause the issues are better for google indexing.

**Comment by jayair** [comment]
Yeah it definitely easier to find and reference.
