### ISSUE TITLE
Cannot perform specific action because there does not exist a valid use pool domain

### ISSUE THREAD

**Issue by QuantumInformation** [AnomalyInnovations/serverless-stack-com#133]
I tried this
```bash
 aws cognito-idp sign-up \
   --region eu-west-2 \
   --client-id 6o3iivoaqbslnqatt46jche42e \
   --username admin@example.com \
   --password Passw0rd!
```
but get this error

An error occurred (InvalidParameterException) when calling the SignUp operation: `Cannot perform specific action because there does not exist a valid use pool domain associated with the user pool`

**Comment by QuantumInformation** [comment]
Solved, had to make a domain in app integration, should this be added to the docs?

**Comment by jayair** [comment]
@QuantumInformation Can you show me what you had to do to get this to work? A screenshot possibly.

**Comment by QuantumInformation** [comment]
In this section in user pools:

![image](https://user-images.githubusercontent.com/216566/30662451-0e2b8980-9e3f-11e7-9a98-3b3a2bc7ff40.png)
![image](https://user-images.githubusercontent.com/216566/30662482-24bdcd34-9e3f-11e7-8491-d0a1891bf2c2.png)

**Comment by jayair** [comment]
@QuantumInformation Thanks for that. I'll take a look.

**Comment by shide1989** [comment]
@quantuminformation  Actualy this is more of a workaround for testing. For production deployment, everything is written in the [aws documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-email.html)
```
Step 2: Move Your Account Out of the Amazon SES Sandbox 
Step 3: Grant Email Permissions to Amazon Cognito
```

**Comment by quantuminformation** [comment]
@manishcronj why the down vote?
