### ISSUE TITLE
Web version instead of PDF?

### ISSUE THREAD

**Issue by QuantumInformation** [AnomalyInnovations/serverless-stack-com#134]
Just to make it easier to copy-paste code?
![image](https://user-images.githubusercontent.com/216566/30595776-1424471e-9d4a-11e7-99f9-4c9fdad7e954.png)

**Comment by jayair** [comment]
@QuantumInformation The tutorial is web based. We just compiled it into the PDF recently. Here is the chapter you are looking for - https://serverless-stack.com/chapters/add-a-create-note-api.html

**Comment by QuantumInformation** [comment]
Great thx

**Comment by progzilla** [comment]
Hi, 

I tried downloading the PDF version but wasn't working after signing up my email. Any help please

**Comment by jayair** [comment]
@progzilla Did you not get an email or did the link in the email not work for you?

**Comment by progzilla** [comment]
@jayair I didn't get any email

**Comment by jayair** [comment]
@progzilla You can send us an email at contact@anoma.ly and we can send it to you.
