### ISSUE TITLE
Sponsors to support this

### ISSUE THREAD

**Issue by QuantumInformation** [AnomalyInnovations/serverless-stack-com#137]
Given this is the best tutorial to help people learn AWS + Seerverless, I think you could ask for sponsors.

**Comment by jayair** [comment]
@QuantumInformation That's a good idea. A few others have suggested something similar as well. I think I might set up a Patreon page for this.

**Comment by QuantumInformation** [comment]
Patreon is a good idea, I would sign up.

**Comment by QuantumInformation** [comment]
Heres where I want to get sponsors for my less well know project:

https://github.com/QuantumInformation/test-recorder#sponsors

**Comment by jayair** [comment]
Thanks for that. Yeah I'll look into Patreon soon.

**Comment by QuantumInformation** [comment]
Good work, I signed up.

**Comment by jayair** [comment]
@QuantumInformation Thanks for the support and the idea itself!
