### ISSUE TITLE
[For discussion] Examples of how you could move more resources into serverless 

### ISSUE THREAD

**Issue by QuantumInformation** [AnomalyInnovations/serverless-stack-com#138]
I don't recommend this being included in the tutorial but it could be useful at the end of the tutorial to explain how things such as identity roles to be configured in serverless yaml instead of manually doing so on the AWS console. 

Could also consider explaining how/if s3 buckets,cognito pool and dynamo DB inside serverless.

**Comment by ahansson89** [comment]
#107

**Comment by QuantumInformation** [comment]
thx mate!

**Comment by jayair** [comment]
@QuantumInformation Yeah we are working on a chapter that we will add to the "Extra Credits" section.
