### ISSUE TITLE
Comments: Configure the AWS CLI

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#14]
Link to chapter - http://serverless-stack.com/chapters/configure-the-aws-cli.html

**Comment by geirman** [comment]
frustratingly stuck at step-1

`zsh: command not found: aws`

I've followed [the instructions here](http://docs.aws.amazon.com/cli/latest/userguide/cli-install-macos.html#awscli-install-osx-path). They advise to add `export PATH=~/.local/bin:$PATH` to my .zshrc profile, but that path doesn't seem to exist and I cannot figure out how to identify the correct path. :-/

**Comment by geirman** [comment]
solved: `brew install awscli`

**Comment by hlgr360** [comment]
On MacOS you can safely ignore the installations on the page and just follow https://docs.aws.amazon.com/cli/latest/userguide/cli-install-macos.html#awscli-install-osx-path

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-configure-the-aws-cli/86
