### ISSUE TITLE
Comments: API Gateway and Lambda Logs

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#146]
Link to chapter - https://serverless-stack.com/chapters/api-gateway-and-lambda-logs.html

**Comment by topguncharl** [comment]
Input for changing instructions due to AWS console "tab changes" -> 
Click tab “Logs”
Checkmark “Enable CloudWatch logs”
Log level -> “INFO”
Checkmark “Log full requests/responses data”
Checkmark “Enable Detailed CloudWatch Metrics”
Click button “Save changes”

**Comment by jayair** [comment]
@topguncharl Thanks for letting us know. Just updated it - 2716a7ef80b7706d181393cfcbc65739fffb5955

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-api-gateway-and-lambda-logs/31
