### ISSUE TITLE
Comments: Debugging Serverless API Issues

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#147]
Link to chapter - https://serverless-stack.com/chapters/debugging-serverless-api-issues.html

**Comment by hollyewhite** [comment]
Hi there! 

Question for you. Might be a newbie one -

When I try to invoke the role in the policy simulator, I don't have the same options as you. Here's what I have: https://screencast.com/t/izAbP7wm Any idea why? 

Trying to troubleshoot a status 403!

Thanks in advance!
-Holly

**Comment by jayair** [comment]
@hollyewhite Yeah it looks like they've changed the interface a bit. But I tried it just now with the same instructions in the tutorial and it worked.

<img width="960" alt="screen shot 2017-11-09 at 1 39 00 pm" src="https://user-images.githubusercontent.com/53023/32623227-6d8e395a-c553-11e7-80b6-1017c282e90d.png">

We'll update the screenshots soon. But let me know if this doesn't work for you.

**Comment by jayair** [comment]
@hollyewhite Just updated the screenshots - https://github.com/AnomalyInnovations/serverless-stack-com/commit/02bb75eeb579f36397bd2402cc7f21e7295ff1ce

**Comment by hollyewhite** [comment]
Thank you @jayair! I appreciate it. I ended up having a credential issue. There are so many! I might hit you up for more questions though. This is my first time building a serverless app and honestly, I don't know how I would have figured it out without this tutorial. You're a rockstar.

**Comment by l0rdr4t** [comment]
I'm currently walking through this tutorial (awesome work, by the way). My apig-test was throwing a "403 Forbidden":

`Message: 'User: arn:aws:sts::123456789012:assumed-role/Cognito_testAuth_Role/CognitoIdentityCredentials is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:ap-southeast-2:********5495:a1b2c3d4e5/prod/POST/notes' }
`

I had to edit the Cognito Auth_Role policy and add the ExecuteAPI service -- this made the API start working, and now I'm wondering if I did something wrong or a step is missing from the Role creation?

**Comment by jayair** [comment]
@l0rdr4t In this chapter - https://serverless-stack.com/chapters/create-a-cognito-identity-pool.html we add a line to the auth role. Is that the one you had to do?

**Comment by l0rdr4t** [comment]
@jayair Thanks for the reply, and yes -- now I know where I went wrong; user error and not the documentation!

In my project, the end user won't be uploading documents to an S3 bucket. I intentionally left out the Policy Action **s3:*** but accidentally left out Policy Action **execute-api:Invoke**, which was in the same code block.

**Comment by jayair** [comment]
@l0rdr4t Thanks for reporting back!

**Comment by mbahfauz** [comment]
Hello I got this message, when I try to add new note. 
"No credentials" Everbody know how to solve it?

**Comment by jayair** [comment]
@mbahfauz Can I see the full error?

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-debugging-serverless-api-issues/33
