### ISSUE TITLE
Comments: Stages in Serverless Framework

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#149]
Link to chapter - https://serverless-stack.com/chapters/stages-in-serverless-framework.html

**Comment by x11joe** [comment]
How do you do staging for the S3 Website side of things, or the React App itself?

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-stages-in-serverless-framework/35
