### ISSUE TITLE
[Offer videos] Youtube

### ISSUE THREAD

**Issue by QuantumInformation** [AnomalyInnovations/serverless-stack-com#152]
I was thinking of making some videos to give an overview of this project if you think that would be useful.

https://www.youtube.com/c/quantuminformation

**Comment by jayair** [comment]
@QuantumInformation Yeah totally, we would love to feature them on here somehow.

**Comment by QuantumInformation** [comment]
Ok hope to make some starting next week.

**Comment by jayair** [comment]
Looking forward to it!

**Comment by QuantumInformation** [comment]
Here it is.
https://www.youtube.com/watch?v=IeWWkhNX79I

**Comment by jayair** [comment]
@QuantumInformation This is really good. I think the video format helps people get more comfortable with the concepts in a way the text based version cannot.

Definitely going to add a link to it from the homepage and we'll send it out to everybody via the newsletter.

Thanks for making these!

**Comment by QuantumInformation** [comment]
happy to help

**Comment by jayair** [comment]
@QuantumInformation Also, let me know when you post the second part of the series.

**Comment by fwang** [comment]
@QuantumInformation Awesome video! You covered many nitty gritty details that wouldn't be possible otherwise through the pure textual format. This is a great supplement to the current tutorial.

**Comment by QuantumInformation** [comment]
thanks @fwang

**Comment by QuantumInformation** [comment]
Next video guys: https://www.youtube.com/watch?v=dnD_f_brSao

**Comment by jayair** [comment]
@QuantumInformation Nice! Do you have a sense of how many videos there are going to be?

**Comment by QuantumInformation** [comment]
Prob another 2 or 3
