### ISSUE TITLE
"serverless deploy" command fails

### ISSUE THREAD

**Issue by TomYeoman** [AnomalyInnovations/serverless-stack-com#153]
I'm unable to progress past chapter : https://serverless-stack.com/chapters/deploy-the-apis.html

![image](https://user-images.githubusercontent.com/14075632/31450402-3a95dc88-aea1-11e7-8c6b-f37ecd198fff.png)

OS: Windows 10
Node version : 8.0.0

No idea what this error is about, could any one help?

e/ Upon retrying to with node v6.1.0 this works fine, perhaps disclaimers should be included if it doesn't work with latest node versions ( Perhaps include a NVM section for downgrading if required )

This is ( unfortunately ) a bit of a turn off to using this stack, as i'm really enjoying out the box support for async / await etc in more recent node versions

**Comment by jayair** [comment]
@TomYeoman That's a weird issue. I'm personally using Node 8.4.0 and a bit of searching turned this up - https://github.com/serverless/serverless/issues/3723.

So it's a Node related issue I'm guessing.

**Comment by TomYeoman** [comment]
Oh yeah, good spot @jayair, I'll close this and update the post then, so it's just node 8.0 that's the issue then how strange. 

Well if anyone could close this ticket and perhaps look to update that chapter with a warning about node 8.0 that would be great :)
