### ISSUE TITLE
Comments: Create an S3 Bucket for File Uploads

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#16]
Link to chapter - http://serverless-stack.com/chapters/create-an-s3-bucket-for-file-uploads.html

**Comment by alexspark** [comment]
![screen shot 2017-08-12 at 4 10 00 pm](https://user-images.githubusercontent.com/1874475/29244234-b9e5a2b4-7f78-11e7-967b-e2f0aa4131b7.png)

Looks like the 3rd part in S3 Bucket creation got an update. Got confused for a few seconds.

**Comment by jayair** [comment]
@alexspark Thanks for letting us know. Updated - https://github.com/AnomalyInnovations/serverless-stack-com/commit/7b324f958fa5a03acd48bbccf3735e24f6964fbb.

**Comment by lucasgonze** [comment]
In the screen shot in the chapter, the owner is admin, which is the IAM user created earlier. However when I created the bucket just now the owner was based on the email for the AWS account. 

This may be significant down the road, given that permissions can lead to baffling issues. If this is significant I can add a user using the name of the IAM role and grant the same permissions as in the default.

**Comment by jayair** [comment]
@lucasgonze Ah. The **admin** is the username on the account we were using and not an AWS thing. I think for this case the default owner should be fine.

**Comment by ondrejpar** [comment]
You should probably mention that using wildcard in CORS configuration is wrong security-wise and definitely should not be used in production environment.

**Comment by jayair** [comment]
@ondrejpar Good point. Just added a note.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-an-s3-bucket-for-file-uploads/90

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-an-s3-bucket-for-file-uploads/150

**Comment by ZaynJarvis** [comment]
There may be a version update. I don't know where can I set the owner for S3 buckets now since it says manage users after creating the bucket.
![image](https://user-images.githubusercontent.com/31875147/50050010-9b2ab680-012b-11e9-89d8-e977ed4a63db.png)

**Comment by ZaynJarvis** [comment]
Oh I'm using the pdf version v3.3.2 for the guide, it seems the issue has been solved in web version.

**Comment by jayair** [comment]
@ZaynJarvis Yeah we'll be updating the PDF shortly.
