### ISSUE TITLE
https://serverless-stack.com/chapters/clear-the-session-on-logout.html is currently "Not Found"

### ISSUE THREAD

**Issue by kdavh** [AnomalyInnovations/serverless-stack-com#164]
Chapter is a dead link. All others before and after that I'm reading work fine.

**Comment by Jaikant** [comment]
This link is not working for me, with a Not Found error:

 https://serverless-stack.com/chapters/create-a-dynamodb-table.html

**Comment by jayair** [comment]
@kdavh @Jaikant That's really weird. Are you guys still seeing this? It seems to be working fine for me now.

**Comment by jayair** [comment]
@kdavh @Jaikant Apparently there was an outage for our hosting provider last night. It should be fine now. Thanks for letting us know.
