### ISSUE TITLE
Comments: Create a Cognito User Pool

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#17]
Link to chapter - http://serverless-stack.com/chapters/create-a-cognito-user-pool.html

**Comment by wilsonmar** [comment]
"App" on the left menu has changed to "App clients"

**Comment by jayair** [comment]
@wilsonmar Thanks, will update it.

**Comment by jayair** [comment]
@wilsonmar Updated - 8185cefd8f1269b443898eff6f5453c8aaa41b94. Thanks for the feedback.

**Comment by jonsaw** [comment]
Question: Update tutorial to use Serverless to setup Cognito?

Like how it's done [here](https://github.com/bsdkurt/aws-node-custom-user-pool)?

😄

**Comment by jayair** [comment]
@jonsaw I see what they are doing but I'm not entirely clear on how we should use it in the tutorial. Could you elaborate a bit?

**Comment by fcostarodrigo** [comment]
![screenshot_20171202_150830](https://user-images.githubusercontent.com/16693844/33517878-fe46c30a-d772-11e7-950c-a157a827ff0a.png)

Cognito was moved from Mobile Services to Security.

**Comment by jayair** [comment]
@fcostarodrigo Thanks. Updated it.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-a-cognito-user-pool/91

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-a-cognito-user-pool/148
