### ISSUE TITLE
Missing "Create new Identity Pool" step

### ISSUE THREAD

**Issue by HoraceShmorace** [AnomalyInnovations/serverless-stack-com#177]
On https://serverless-stack.com/chapters/create-a-cognito-identity-pool.html:

In between the "Select **Manage Federated Identities**" step, and the "Enter an **Identity pool name**" step, there should be a step to "Select **Create new Identity Pool**."

**Comment by jayair** [comment]
@HoraceShmorace I guess that happens when a user has existing identity pools in their account. Just added a note. Thanks.
