### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by kwhitejr** [AnomalyInnovations/serverless-stack-com#180]
This is a great tutorial, but I'm having a damnable time figuring out how to properly unit test the lambdas. Are there recommended methodologies for unit testing async lambdas? Do we mock the DynamoDB?

**Comment by jayair** [comment]
@kwhitejr Mocking is one way to do it. You can also use [DynamoDB Local](https://github.com/99xt/serverless-dynamodb-local).

Personally, we use unit tests on the parts of our code that are side-effect free. So we separate the actual DB call out. And integration tests would hopefully help cover the side-effect portions for you.

**Comment by kwhitejr** [comment]
So, from this tutorial, you would unit test the `/libs/*` functions rather than the completed handlers, e.g. `/get.js`?

**Comment by jayair** [comment]
@kwhitejr This function is pretty simplistic so the unit tests won't be useful here. But I would probably refactor the code to do something like this:

```
getDBParam(event) => params
dbResultToResponse(result) => response
```

Where `params` in the `getDBParam` is simply returning the params object in the code above. In the test I would ensure that it handles invalid inputs for the `event` object. Not a terribly useful test for this case.

For the `dbResultToResponse` it takes what the db call returns, `result` and it would return success or failure with the item or the error. And I would test if this function handles the db results. Again, not too useful for this example.

Hope that helps.

**Comment by kwhitejr** [comment]
@jayair Every little bit helps, thanks for the advice! I'm at the beginning of my test-writing career, so I value any input. I see why those abstractions are not terribly useful, but they are illustrative in a helpful way. Thanks!

**Comment by jayair** [comment]
Great. I'll close this issue for now.
