### ISSUE TITLE
image for deselect Use default settings

### ISSUE THREAD

**Issue by valmonaco** [AnomalyInnovations/serverless-stack-com#182]
In chapters/create-a-dynamodb-table.html the instructions given are:
   If you see the following message, deselect **Use default settings**.

The image below this instruction ( serverless-stack-com/assets/dynamodb/auto-scaling-iam-role-warning.png)  shows a check in the checkbox next to Use default settings.  I believe that the image would be clearer showing the checkbox deselected (to match the intended state).  Attaching adjusted image.
![auto-scaling-iam-role-warningv2](https://user-images.githubusercontent.com/26844121/35199573-fb2d44d2-fecd-11e7-88c5-bdc615fea62f.png)

**Comment by jayair** [comment]
@valmonaco Yeah that makes sense. Adding it in. Thanks for taking the screenshot and formatting it the right way.
