### ISSUE TITLE
Facebook/Google social integration using USER POOL custom UI.

### ISSUE THREAD

**Issue by jatazoulja** [AnomalyInnovations/serverless-stack-com#187]
hey!

hope this helps...  
**## just a caveat:** 

- I am using user pool custom UI not federated identity... 
- I'm still debugging as of the moment. 

for the function in the `awsLibs.js`

I added:
https://gist.github.com/jatazoulja/a0cfcf23cf8a55e5306e1ebda58f680e

On your route add:
`<UnauthenticatedRoute path="/oauth" exact component={OAuth} props={childProps} />`
* please note to add "/" on your Callback URL(s) "http://localhost:3000/oauth/"

On your `OAuth` component:
```
    getHashValue(key) {
        var matches = window.location.hash.match(new RegExp(key + '=([^&]*)'));
        return matches ? matches[1] : null;
    }
    render() {
        const { match } = this.props;
        window.opener.postMessage({
            AccessToken: this.getHashValue('access_token'),
            ExpiresIn: this.getHashValue('expires_in'),
            IdToken: this.getHashValue('id_token'),
            TokenType: this.getHashValue('token_type')
        }, '*');

        window.close();

        return (<p>

        </p>)
    }
```
**## SOURCE**
[https://github.com/aws/amazon-cognito-identity-js/issues/508](https://github.com/aws/amazon-cognito-identity-js/issues/508)

**Comment by jayair** [comment]
@jatazoulja This is great. Once you work your way through it. Can you share the steps you took to get it to work?

**Comment by jatazoulja** [comment]
Will do! currently i am planning to 2 environment (localhost, devhost). I'll document my steps for everyone.

Once i integrated social its really hard to toggle between localhost and dev environment. Since i need to configure FB and cognito to point to local and back to devhost.

**Comment by jatazoulja** [comment]
closing this one; 

1. Wrong PROJECT;
2. I already made a PR ([the right project.](https://github.com/AnomalyInnovations/serverless-stack-demo-client/pull/26))
