### ISSUE TITLE
Containers vs. Components in instructions

### ISSUE THREAD

**Issue by seanofahey** [AnomalyInnovations/serverless-stack-com#191]
Thanks for the excellent tutorial.  This is a minor suggestion on your documentation on this page https://serverless-stack.com/chapters/handle-404s.html  

The prior page of the instructions have you set up the "components" directory in addition to the existing "containers" directory and thus introduces **components** and **containers** as different concepts.  On this page, though your instructions call NotFound.js a component but has you put the code in the containers directory.

**Comment by jayair** [comment]
@seanofahey Yeah that's a good point. We didn't really cover the difference as much. Basically, we use containers as components that handle routes and API requests as well. Components on the other hand are "dumb" React components.
