### ISSUE TITLE
Problem with Navbar.Collapse on the non-mobile device

### ISSUE THREAD

**Issue by staskh** [AnomalyInnovations/serverless-stack-com#195]
Hi,

Sorry for bothering, but I seem can't find a bug after hours of looking around.

Example code was working well for a while until for some reason Navbar begin to be rendered as if it be a mobile web interface.   I'm using the same Chrome and Safari on MacOS.

Nice navigation bar disappeared and I have only collapsing button left from "Scratch" text. Clicking on this button open submenu for few seconds, but do not allow me to click on submenue items.

All code App.js seems to be equivalent to one form your GIT. Please help.

**Comment by jayair** [comment]
@staskh Which chapter was it that you were working on?

**Comment by staskh** [comment]
Apparently the problem I observed related to Bootstrap/ React-Bootstrap version mismatch. Your fix https://github.com/AnomalyInnovations/serverless-stack-demo-client/compare/v1.2.4...v1.2.5 did a magic.
