### ISSUE TITLE
Comments: Set up the Serverless Framework

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#21]
Link to chapter - http://serverless-stack.com/chapters/setup-the-serverless-framework.html

**Comment by Hollow27** [comment]
![node1](https://cloud.githubusercontent.com/assets/17459855/26134378/3808e33c-3a7c-11e7-82b9-4dc63be15ae3.JPG)
![node2](https://cloud.githubusercontent.com/assets/17459855/26134377/3807cd12-3a7c-11e7-92db-11e3bdb44b0c.JPG)
![node3](https://cloud.githubusercontent.com/assets/17459855/26134380/380c1958-3a7c-11e7-9dca-f0af4ff901f1.JPG)
![node4](https://cloud.githubusercontent.com/assets/17459855/26134379/380a00a0-3a7c-11e7-8557-87011fcf8252.JPG)


I'm having another problem here as well creating an aws node.js service...any input would be greatly apppreciated!

**Comment by fcostarodrigo** [comment]
Why `aws-sdk` was installed as a `devDependencies`? Shouldn't it be installed in `dependencies` instead?

**Comment by jayair** [comment]
@fcostarodrigo This portion of the setup is weird but better explained here - https://github.com/serverless-heaven/serverless-webpack#node-modules--externals

**Comment by fcostarodrigo** [comment]
I see. AWS already includes `aws-sdk`, so you don't need to include it again.

http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html

**Comment by jayair** [comment]
Yup

**Comment by topguncharl** [comment]
in last ls response is 5 files not 4 -> handler.js		node_modules		package-lock.json	package.json		serverless.yml

**Comment by jayair** [comment]
@topguncharl Thanks for the heads up. Tweaked the wording in the chapter.

**Comment by mgeiser** [comment]
Under the "Install Node.js packages" section, you say "At the root of the project, run."

It would be helpful to disambiguate by confirming the root of the project; I assume this is not the notes-app-api directory but the parent directory

**Comment by mgeiser** [comment]
ok, I guess it was notes-app-api...

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-set-up-the-serverless-framework/79

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-set-up-the-serverless-framework/145
