### ISSUE TITLE
unexpected token in create.js with newer node version? 

### ISSUE THREAD

**Issue by stcalica** [AnomalyInnovations/serverless-stack-com#215]
`export async function main(event, context, callback) {`

I have this in my `create.js` but I keep getting this error: 

```
SyntaxError: Unexpected token function
    at Object.a../create.js (/Users/kyle.calica-steinhil/Code/serverless-react/notes-app-api/.webpack/service/create.js:88:1)
```

This is after we refactored into the libs. 

After looking into it I found a StackOverflow that claims this not the proper way to use `async` with `function` anymore. Or am I wrong and my babel configuration is wrong? Just need help to make it to the next part, please. 

StackOverflow in Question: 

https://stackoverflow.com/questions/37815790/syntaxerror-unexpected-token-function-async-await-nodejs

**Comment by jayair** [comment]
@stcalica Yeah I don't think your project is configured properly. Can you compare your `package.json`, `serverless.yml`, and `webpack.config.js` to the one from the tutorial - https://github.com/AnomalyInnovations/serverless-stack-demo-api/tree/add-support-for-es6-es7-javascript?

**Comment by stcalica** [comment]
so I actually just went in and pasted them in. Originally I actually tried writing them in myself. 
But now I'm stuck with `Unexpected token function`

```
SyntaxError: Unexpected token function
    at Object.a../create.js (/Users/kyle.calica-steinhil/Code/serverless-react/notes-app-api/.webpack/service/create.js:88:1)

```

Offending line: 
`
eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"main\", function() { return main; });\n/* harmony import */ var uuid__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! uuid */ \"uuid\");\n/* harmony import */ var uuid__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(uuid__WEBPACK_IMPORTED_MODULE_0__);\n/* harmony import */ var _libs_dynamodb_lib__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./libs/dynamodb-lib */ \"./libs/dynamodb-lib.js\");\n/* harmony import */ var _libs_response_lib__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ./libs/response-lib */ \"./libs/response-lib.js\");\n\n\n\n\nasync function main(event, context, callback) {\n  const data = JSON.parse(event.body);\n  const params = {\n    TableName: \"notes\",\n    Item: {\n      userId: event.requestContext.identity.cognitoIdentityId,\n      noteId: uuid__WEBPACK_IMPORTED_MODULE_0___default.a.v1(),\n      content: data.content,\n      attachment: data.attachment,\n      createdAt: new Date().getTime()\n    }\n  };\n\n  try {\n    await _libs_dynamodb_lib__WEBPACK_IMPORTED_MODULE_1__[\"call\"](\"put\", params);\n    callback(null, Object(_libs_response_lib__WEBPACK_IMPORTED_MODULE_2__[\"success\"])(params.Item));\n  } catch (e) {\n    callback(null, Object(_libs_response_lib__WEBPACK_IMPORTED_MODULE_2__[\"failure\"])({ status: false }));\n  }\n}\n\n//# sourceURL=webpack:///./create.js?");`

Now this is with everything being copypasted. So I don't know what other errors I can do from here?

**Comment by stcalica** [comment]
kyle$ node --version
v6.3.0
kyle$ npm --version
4.0.3
kyle$ serverless --version
1.26.1

**Comment by jayair** [comment]
@stcalica Yeah we need at least Node v8.10 for this. Since we are targeting Lambda functions that recently updated to v8.10.

**Comment by stcalica** [comment]
just updated node, it's not working. It runs without error. but doesn't even print out my simple print statements.
I copied the code from the site as well. hmmmm

**Comment by stcalica** [comment]
`serverless invoke local --function create --path mocks/create-event.json`

**Comment by jayair** [comment]
@stcalica That looks good. What does your `package.json` look like?

**Comment by stcalica** [comment]
```
kyle$ cat package.json 
{
  "name": "notes-app-api",
  "version": "1.0.0",
  "description": "",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "aws-sdk": "^2.221.1",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-3": "^6.24.1",
    "serverless-webpack": "^5.1.1",
    "webpack": "^4.5.0",
    "webpack-node-externals": "^1.7.2"
  },
  "dependencies": {
    "babel-runtime": "^6.26.0",
    "uuid": "^3.2.1"
  }
}

```

I'm hoping I just need to update something. Maybe in the front of the site or end you can keep an udpated `package.json`? I'd be happy to contribute to that and keep it updated if you want help if that'd be too much of a nuisance.

**Comment by jayair** [comment]
@stcalica Hmm that looks okay. We link to the repo at the end of major chapters - https://github.com/AnomalyInnovations/serverless-stack-demo-api/blob/master/package.json.

I don't think this error is related to the project. Which OS are you on?

**Comment by stcalica** [comment]
I'm on MAC OSX El Captain. 

Damn that's discouraging. Have no idea how to continue with this then. :/

**Comment by jayair** [comment]
@stcalica You can try running the debug version of the command `SLS_DEBUG=* serverless invoke local --function create --path mocks/create-event.json`.

**Comment by mystaticself** [comment]
@jayair Same issue here, no response output. This is what I get running the debug version. You ever get this sorted, @stcalica?

> Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Invoke invoke:local

**Comment by stcalica** [comment]
sadly no. and no work around ever worked. had to abandon tutorial and just learn from scratch unfortunately :/

**Comment by mystaticself** [comment]
that's a shame. may have to do the same.

**Comment by jayair** [comment]
I'm not sure what is causing this issue for you guys. But can you put up your repo on GitHub and post the command? I'll give it a try on my end.

**Comment by stcalica** [comment]
dang i had to delete my repo if i recall, i just updated my OSX maybe that was the problem? 
I'll try the tutorial again and let you know.

**Comment by TheGodEmperor** [comment]
So you need node 8.10+? That's disappointing because Red Hat Fedora 7 only supports up to 6 right now.

**Comment by jayair** [comment]
@TheGodEmperor There isn't one sadly. Node.js has now made v8.11 Active LTS. But the code changes aren't large that if you know about Promises and exports, you could work around it.

**Comment by stcalica** [comment]
Wow! I did not realize how long ago I tried this. 
I re-did it and I am able to do this now. I am on Catalina btw. 
I also have better JS skills and npm/nvm/node knowledge now. 
You can close this out if you like.

**Comment by jayair** [comment]
Awesome!
