### ISSUE TITLE
Reactive data in GUI

### ISSUE THREAD

**Issue by jonasbarsten** [AnomalyInnovations/serverless-stack-com#230]
Hi :)

How can I make the GUI reactive (if that’s the right word).

For example when I see all my notes in the GUI and I manually remove/edit/add a note from the DynamoDB console, I want the GUI to reflect that without reloading.

Websocket? Streams?

**Comment by jayair** [comment]
@jonasbarsten Hmm I'm not entirely sure. I guess it would be Websockets.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/reactive-data-in-gui/15
