### ISSUE TITLE
Inaccessible host: `cognito-idp.your.amazonaws.com'.

### ISSUE THREAD

**Issue by ringoyip0901** [AnomalyInnovations/serverless-stack-com#231]
Link: https://serverless-stack.com/chapters/test-the-apis.html

When I was testing the API gateway, I got the following message in the terminal: "Inaccessible host: `cognito-idp.your.amazonaws.com'. This service may not be available in the `YOUR' region."

Is it possibly due to the S3 bucket itself, or some other things that I am not yet aware of? Thank you so much.

**Comment by jayair** [comment]
@ringoyip0901 Some times that happens when that host is not accessible (internet connectivity issues). But what does your full command look like?

**Comment by ringoyip0901** [comment]
@jayair thank you for the reply! I use a mac so I use the same command as the tutorial shows: 
"npx aws-api-gateway-cli-test \
--username='admin@example.com' \
--password='Passw0rd!' \
--user-pool-id='YOUR_COGNITO_USER_POOL_ID' \
--app-client-id='YOUR_COGNITO_APP_CLIENT_ID' \
--cognito-region='YOUR_COGNITO_REGION' \
--identity-pool-id='YOUR_IDENTITY_POOL_ID' \
--invoke-url='YOUR_API_GATEWAY_URL' \
--api-gateway-region='YOUR_API_GATEWAY_REGION' \
--path-template='/notes' \
--method='POST' \
--body='{"content":"hello world","attachment":"hello.jpg"}'"

I made sure every piece of information was provided correctly. I'm pretty sure the internet was also working when I ran the command though. What other possibilities are there?
