### ISSUE TITLE
Proposal : add a copy button for all copy-paste stuff which is spread a lot in this book.

### ISSUE THREAD

**Issue by erdahuja** [AnomalyInnovations/serverless-stack-com#255]
Manually doing it with mouse is cumbersome.

**Comment by jayair** [comment]
@erdahuja That's a pretty good idea. I need to look into how to do this.

**Comment by erdahuja** [comment]
@jayair I can implement it.

One more thing is super odd about this book. I read it completely, but the main article should be separately scrollable instead of the whole page. I need quick access to index soi to have to scroll back up to reach there.

**Comment by jayair** [comment]
@erdahuja Yeah I can see that. I want to do this without adding a ton of javascript to the page.

It'll be great if you are interested in implementing these. You can join our Gitter here - https://gitter.im/serverless-stack/Lobby and I can help get you started.

**Comment by pepas24** [comment]
Hi, is anyone working on this? I want to contribute in small features like this to start getting involved in open source.

**Comment by jayair** [comment]
@pepas24 I don't think anybody is working on it right now. But if you'd like to help out, message me here https://gitter.im/serverless-stack/Lobby and I can help you get started.

**Comment by pepas24** [comment]
This feature has just been implemented in https://github.com/AnomalyInnovations/serverless-stack-com/commit/49be6f2569bb8176e418bcae3fa027a4b888c09a
