### ISSUE TITLE
Comments: Add an Update Note API

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#26]
Link to chapter - http://serverless-stack.com/chapters/add-an-update-note-api.html

**Comment by oluckyman** [comment]
why use 
`    ReturnValues: 'ALL_NEW',`
if the response returns `success: true` only?

**Comment by fwang** [comment]
You are totally right. We are not using the results any where in the code. It is in there in case users want to inspect the return value just for learning purposes.

Feel free to set ReturnValues to 'NONE' or remove the line.

**Comment by oluckyman** [comment]
cool, thanks!
and thanks for the content, great material and easy to read. I like how you
balance explaining things and avoiding rabbit holes, without overwhelming
with too much information

**Comment by akolybelnikov** [comment]
Thank you for the great material! It's very easy to follow and understand.
However, I am getting status 500 with the update API and I cannot find where the error is coming from because all I get to see in response is "status":"false". All other API are working and I can create, delete and list the mocked objects.

**Comment by walshe** [comment]
wouldn't it be a good idea to use a 'version' field for an optimistic locking approach ?

**Comment by jayair** [comment]
@walshe Do you mean a version to keep track of the edits made to a note? You can definitely do that! We are just keeping it fairly simple in the tutorial.

**Comment by walshe** [comment]
@jayair not exactly, I am talking about handling concurrent updates, so that if an entity has changed between the time it takes someone to read and update the entity then the update would fail similar to an 'update x set a=, b=,c= where version=<expectedversion>'

**Comment by jayair** [comment]
@walshe Oh yeah I see what you are saying. That is definitely a good idea. I think we could cover it in an advanced chapter maybe?

For anybody else reading this; if two users are editing the same note, one could overwrite the other since we simply update the note with the passed in content. By adding a `version` field we can ensure that the note we are editing is the current version of it (as opposed to one that has already been updated in Dynamo).

**Comment by walshe** [comment]
yeah I think you just need a condition expression in the update

**Comment by allasandeep** [comment]
I am getting this error, can anyone help me?

serverless invoke local --function update --path mocks/update-event.json

  Y A M L Exception --------------------------------------

  duplicated mapping key in "C:\Users\gayat\Desktop\project-app-api\serverless.yml" at line 75, column 5:
        handler: update.main
        ^

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.10.0
     Serverless Version:     1.26.1

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-add-an-update-note-api/77

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-add-an-update-note-api/144
