### ISSUE TITLE
Omitted verbs in Setup a Strip Account Chapree

### ISSUE THREAD

**Issue by davidmsvetlecic** [AnomalyInnovations/serverless-stack-com#264]
This sentence:
"The second thing to is the Publishable key and the Secret key."    should read?
"The second thing to (do?) is (generate?) the Publishable key and the Secret key."

**Comment by davidmsvetlecic** [comment]
or better (to match paragraph above this one):
The second thing to (note?) is (generate?) the Publishable key and the Secret key

**Comment by davidmsvetlecic** [comment]
or:
The second thing to (note?) is ((that) we need to generate?) the Publishable key and the Secret key

**Comment by davidmsvetlecic** [comment]
or:
The second thing to (note?) is ((that) we need to generate?) the Publishable key and the Secret key.

**Comment by jayair** [comment]
Thanks for pointing it out! Fixing it now.
