### ISSUE TITLE
Comments: Add a Delete Note API

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#27]
Link to chapter - http://serverless-stack.com/chapters/add-a-delete-note-api.html

**Comment by justDanielMata** [comment]
Hello! i have a pretty weird issue with this chapter, all the other endpoints worked fine, but in this one i get a type error: cannot read property 'handler' of undefined...it prompts me to run on debug mode, but i have no idea where to put the env variable for that, any help?

**Comment by jayair** [comment]
@justDanielMata usually, that means that Serverless is not able to find the `handler` property in the `serverless.yml`. Try comparing yours to the one from the chapter and make sure it looks okay - https://github.com/AnomalyInnovations/serverless-stack-demo-api/blob/add-a-delete-note-api/serverless.yml

**Comment by justDanielMata** [comment]
thanks for the fast answer, copying the whole functions part on the code seemed to fix it, but i have no idea what happened, fwiw, i wrote the update code myself instead of copy pasting, maybe had identation issues? (i know nothing about yml)

**Comment by jayair** [comment]
@justDanielMata Yeah indentations are usually the cause for this. Tabs as opposed to spaces can cause it too.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-add-a-delete-note-api/82

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-add-a-delete-note-api/153
