### ISSUE TITLE
What about a version of React App using ReasonML?

### ISSUE THREAD

**Issue by daniloraisi** [AnomalyInnovations/serverless-stack-com#276]
I'm starting doing some projects with React + ReasonML and I can help with this task too.

**Comment by jayair** [comment]
Awesome! Yeah that would make a great addition to the chapters. We could use:

- A Reason version of the Nodes app in a repo
- And some steps on how to set it up and deploy it

Let me know if that is something you can help with.

**Comment by daniloraisi** [comment]
> Awesome! Yeah that would make a great addition to the chapters. We could use:
> 
> * A Reason version of the Nodes app in a repo
> * And some steps on how to set it up and deploy it
> 
> Let me know if that is something you can help with.

Set it up and deploy is as easy as on a regular approach.

I think the main change is really develop in an functional way.

I'll start mapping necessary bindings to get AWS Amplify working on ReasonML.

**Comment by jayair** [comment]
Awesome. You can message me through https://gitter.im/serverless-stack/Lobby if you have any questions.
