### ISSUE TITLE
Comments: Create a New React.js App

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#29]
Link to chapter - http://serverless-stack.com/chapters/create-a-new-reactjs-app.html

**Comment by dannjoku1** [comment]
npm ERR! missing script: start <--- can anyone help me figure out why this is happening?

**Comment by jayair** [comment]
@dannjoku1 I think there might an issue with your `package.json`. Can you compare it to the one in the tutorial?

https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/create-a-new-reactjs-app/package.json

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-a-new-react-js-app/68
