### ISSUE TITLE
Comments: Add App Favicons

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#30]
Link to chapter - http://serverless-stack.com/chapters/add-app-favicons.html

**Comment by lepirlouit** [comment]
When users install your app to the homescreen of their device the default configuration will make a shortcut to `/index.html`. This may not work for client-side routers which expect the app to be served from `/`. Edit the web app manifest at `public/manifest.json` and change `start_url` to match the required URL scheme, for example:

`  "start_url": ".",`

see : https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#serving-apps-with-client-side-routing

**Comment by jayair** [comment]
@lepirlouit Can you verify that this change works on Android? If it does I'll update the tutorial.

**Comment by lepirlouit** [comment]
I confirm, I tested this and this works on android lollipop.

**Comment by jayair** [comment]
@lepirlouit Awesome thanks. I'll update it.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-add-app-favicons/85

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-add-app-favicons/155
