### ISSUE TITLE
Typo on "Signup with AWS Cognito" page

### ISSUE THREAD

**Issue by AmoDinho** [AnomalyInnovations/serverless-stack-com#315]
Hi! Found this minor typo in the try block of `/signup.js` on the tutorial's website, where it should be calling the `signUp` method and not Amplify's `signIn` method:

This is on the site
```
try {
   ...
    await Auth.signIn(this.state.email, this.state.password);
....
}

```

while in the repo it is: 

```
try {
    ...
    await Auth.signUp(this.state.email, this.state.password);
   ....
}

```

**Comment by AmoDinho** [comment]
Apologizes, I realized that this is not a typo but an attempt to sign in after confirming the confirmation code. 💀

**Comment by jayair** [comment]
No worries!
