### ISSUE TITLE
Inaccessible host: `cognito-identity.xn--us-west-3-499dua.amazonaws.com'.

### ISSUE THREAD

**Issue by ArthurG** [AnomalyInnovations/serverless-stack-com#328]
Link: https://serverless-stack.com/chapters/test-the-apis.html

When I am testing my API, I get the following error message: 
Inaccessible host: `cognito-identity.xn--us-west-2-499dua.amazonaws.com'. This service may not be available in the `‘us-west-2’' region.

Any help?

**Comment by jayair** [comment]
Can you post this on our forums?https://discourse.serverless-stack.com/t/comments-for-test-the-apis/122
