### ISSUE TITLE
Improve confusing instructions when creating a note

### ISSUE THREAD

**Issue by MattDelmarter** [AnomalyInnovations/serverless-stack-com#335]
In the "Test" section of the following page:
https://serverless-stack.com/chapters/add-a-create-note-api.html#test

The instructions say to:

```
$ mkdir mocks
$ cd mocks
```

However all the following commands need to be run from the current direction, not the `mocks` directory. i.e. the following line should be removed...

```
$ cd mocks
```

**Comment by jayair** [comment]
Good catch. Thanks for pointing it out. Fixed.
