### ISSUE TITLE
Status: 404

### ISSUE THREAD

**Issue by abhinavjonnada82** [AnomalyInnovations/serverless-stack-com#344]
Hello,
I've been getting below error:
```
`Authenticating with User Pool
Getting temporary credentials
Making API request
{ status: 404,
  statusText: 'Not Found',
  data:
   { message: 'No method found matching route / for http method POST.' }`
```
This is my command 
```
npx aws-api-gateway-cli-test --username='test@t.com' --password='Admin123!' --user-pool-id='us-east-1_n2u1yS41s' --app-client-id='1lmq66tkudd4ajiak3vhginpam' --cognito-region='us-east-1' --identity-pool-id='us-east-1:0d942a90-e09a-4bbe-96be-5df6436c813f' --invoke-url='https://1d2k7e1xkf.execute-api.us-east-1.amazonaws.com/prod' --api-gateway-region='us-east-1' --path-template= '/notes' --method='POST' --body='{"content":"hello world","attachment":"hello.jpg"}'
```
and I've cross checked twice can someone help me.
Thank you in advance.

**Comment by abhinavjonnada82** [comment]
@jayair @bernardobugmann  Can you help me out!!

**Comment by jayair** [comment]
Hi there, can you post this to the relevant chapter on https://discourse.serverless-stack.com. Thanks!

**Comment by abhinavjonnada82** [comment]
@jayair just did that with an updated response!!

**Comment by owenashurst** [comment]
> @jayair just did that with an updated response!!

I know this was nearly a year ago, but if you resolved this can you please post here the solution for other people?

**Comment by jayair** [comment]
If you are looking for help with the guide head over to the forums instead — https://discourse.serverless-stack.com
