### ISSUE TITLE
Add the Session to the State

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#39]
Link to chapter - https://serverless-stack.com/chapters/add-the-session-to-the-state.html

**Comment by KelpDuNord** [comment]
When running a Jest test against App.js, I get "Unexpected token" at the = after userHasAuthenticated in 
userHasAuthenticated = authenticated => {
this.setState({ isAuthenticated: authenticated });
}
The syntax seems correct according to the React docs. Anyone have a clue? Thanks.

**Comment by jayair** [comment]
@KelpDuNord Yeah the syntax looks fine. I'm not sure why it's complaining.

**Comment by x11joe** [comment]
`<RouteNavItem key={1} href="/signup">` I noticed you added key={1} but the section does not explain why (or even if the reason why is because it will be used later).  Curious what this is needed for?

**Comment by jayair** [comment]
@x11joe React needs keys when you are creating a list of components. You can read more about it here - https://reactjs.org/docs/lists-and-keys.html

**Comment by lucasgonze** [comment]
I find this bit of code particularly baffling:

`export default ({ component: C, props: cProps, ...rest }) =>
  <Route {...rest} render={props => <C {...props} {...cProps} />} />;`

The combo of ES6 with React idioms in the context of shorthand code makes it inscrutable.

**Comment by TheDagger** [comment]
@lucasgonze yeah I agree I had to spend like an hour wrapping my head around that the first time lol

**Comment by jayair** [comment]
@lucasgonze @TheDagger Yeah I can see that. Let me add more of an explanation to that section.

**Comment by jayair** [comment]
Just added a better explanation - https://github.com/AnomalyInnovations/serverless-stack-com/commit/6be7f67ae12dd4619c842c8b0a86a282ce628fd2

**Comment by x11joe** [comment]
I had one more question on this section, the code `<Route {...rest} render={props => <C {...props} {...cProps} />} />;` I get most of this now, but the part I don't get in particular is  `{...props} {...cProps} />}`.  My understanding is this creates the properties and the values that go with the properties.  This makes sense except for one thing.  My understanding of attributes is it has to be formatted like this, <a href**=**"hey" custom**=**"something">test</a>.  I bolded the = here because I noticed that is not in the example but somehow it still works? How is this working with the equal omitted?

**Comment by jayair** [comment]
@x11joe I agree this part is pretty confusing. And JSX has not been my favorite feature of React but it ends up being fairly convenient in practice.

In this specific case, your idea is right. The spread operator `{...props}` does it for you. Here is more info on it - https://reactjs.org/docs/jsx-in-depth.html#spread-attributes. The entire chapter is worth a read if you want to get a better understanding of JSX.

**Comment by teejK** [comment]
JS noob here: originally read `{component: C, props: cProps, ...rest}` as an object,
but `C` and `cProps` are aliases for `component` and `props`.

`export default ({ component: C, props: cProps, ...rest })`
> Finally, we take component (set as C) and props (set as cProps) 

Could you name this behaviour so I can look up documentation for it or link to documentation for this behaviour so I can better understand how/when to use it?

**Comment by jayair** [comment]
@teejK Yeah it's called Destructuring https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

**Comment by kevinlbatchelor** [comment]
Writing unreadable code like this is ridiculous, we write code for people to read not computers.

 `export default ({ component: C, props: cProps, ...rest }) => <Route {...rest} render={props => <C {...props} {...cProps} />} />;`

the spread operator is still tricky, but here is the same code written more verbosely, and perhaps easier to read, which IMO should be apart of an good tutorial 

`import React, {Component} from 'react';
import {Route} from 'react-router-dom';

export default class AppliedRoute extends Component {

    render() {
        const Comp = this.props.component;
        const childProps = this.props.props;
        const exact = this.props.exact;
        const path = this.props.path;

        return (
            <Route path={path} exact={exact} render={(routerProps) => {
                return (
                    <Comp {...routerProps} {...childProps}/>
                );
            }}/>
        );
    }
};`

**Comment by jayair** [comment]
@kevinlbatchelor While what you are saying is true; I get plenty of comments from other folks who look at a simplified version and tell us that we should use the "modern version" because it's more "efficient".

That said, I do think code like this (as it is in a lot of other languages) will become more common as it gets adopted. There are going to be some growing pains for the JS world. In fact, this line is taken from the React Router docs which I assume some of our readers will try and go over.

This is why I decided to leave it this way but added a long explanation on how some of destructuring parts work - https://github.com/AnomalyInnovations/serverless-stack-com/commit/6be7f67ae12dd4619c842c8b0a86a282ce628fd2

Thanks for your comment. It'll help anybody else that is looking for a simpler way to write this. And I understand your frustration.

**Comment by twalkerjr22** [comment]
Does anyone know how to fix this error? TypeError: _this.props.userHasAuthenticated is not a function. (In '_this.props.userHasAuthenticated(true)', '_this.props.userHasAuthenticated' is undefined)

**Comment by jayair** [comment]
@twalkerjr22 Where exactly are you seeing this?

**Comment by caronicolas** [comment]
I have the same error as @twalkerjr22 . The error appear in a popup when I try to log in.
I have read again the complete part two times but I don't find what I'm doing wrong...

**Comment by jayair** [comment]
@caronicolas Can you tell me exactly after which step in the tutorial do you start seeing this error?

**Comment by alex-romanov** [comment]
@jayair, I have the same error as @carnicolas, the error is comes from within the try statement in the handleSubmit function in Login.js

**Comment by caronicolas** [comment]
It's just after this step : 

> Replace the alert('Logged in'); line with the following in src/containers/Login.js.
> this.props.userHasAuthenticated(true);

**Comment by caronicolas** [comment]
Ok, thank you @alex-romanov, I insert a space between childProps and '=' sign... My bad... Sorry @jayair

**Comment by jayair** [comment]
@alex-romanov @caronicolas Glad you figure it out.

**Comment by d3lusional** [comment]
I am having the same issue with "this.props.userHasAuthenticated" is not a function. Unfortunately my problem wasn't the <Routes childProps={childProps} />

**Comment by jayair** [comment]
@d3lusional What's the issue you are having?

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/add-the-session-to-the-state/136
