### ISSUE TITLE
Question on Amplify config 

### ISSUE THREAD

**Issue by andreimcristof** [AnomalyInnovations/serverless-stack-com#398]
Hi, this is a question, not an issue: 
In the step "Configure AWS Amplify", in the [Serverless Stack guide](https://serverless-stack.com/chapters/configure-aws-amplify.html), all the config is placed in an config.js in the /src folder. 

My question is: is it not a security flaw, to expose such infrastructure details like S3 Bucket Name and Cognito IDs in the js file, and send them to the browser? I understand exposing the API urls and region, but is it ok to also expose the rest of that config.js file?
Thanks in advance,

**Comment by jayair** [comment]
Those are completely fine. The access to those resources are restricted by authentication. And we don't allow unauthenticated access to them.

**Comment by andreimcristof** [comment]
Thank you!
