### ISSUE TITLE
Comments: Load the State from the Session

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#40]
Link to chapter - http://serverless-stack.com/chapters/load-the-state-from-the-session.html

**Comment by yashg5** [comment]
what if user token expires?  do we need to re-login to get the fresh token?

**Comment by jayair** [comment]
@yashg5 The token does expire after an hour but the way the app is set up, when the user refreshes the page we check the session in the Local Storage (the SDK does this) and re-load it.

However, there is a corner case that we are not handling. If the user does not refresh the page within an hour, then the token will expire and you'll get an error. We are going to put out an update to address this soon. But you can easily handle this yourself.

**Comment by teejK** [comment]
Hey, I'm new to javascript, so maybe this is a noob question. 
But, we seem to define componentDidMount without calling it? 

Do async class methods get called automatically? I can't seem to suss out where it gets called.

**Comment by jayair** [comment]
@teejK No worries. Yup part of the React component lifecycle.

**Comment by Mutley5000** [comment]
Hi,
Just a note that there was no mention to create the userHasAuthenticated method.

  userHasAuthenticated = authenticated => {
    this.setState({ isAuthenticated: authenticated });
  }

Also I believe NavItem needs to be added back into:
  import { Nav, NavItem, Navbar } from "react-bootstrap";
which was not mentioned either.

Kind regards,
Braydon

**Comment by TheDagger** [comment]
I have a newbie question as well, the line `!this.state.isAuthenticating &&` proceeds after the && to follow with the page to be rendered.  How is this working exactly? The way I understand return functions is they return content, true or false.  So if the state is currently authenticating it will return true && the content? How do you return both? This is the part that doesn't make sense to me.

**Comment by jayair** [comment]
@TheDagger Yeah that line is basically using [short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation) to conditionally render our component.

> The short-circuit expression `x and y` is equivalent to the conditional expression `if x then y else false`...

So if `!this.state.isAuthenticating` is true then render our component (return the JSX) or just return false.

Hopefully that makes sense.

**Comment by lepirlouit** [comment]
It seems not to be a best practice to call setState in the componentDidMount function.


https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-did-mount-set-state.md

**Comment by jayair** [comment]
@lepirlouit According to the React docs it is okay to call `setState` in `componentDidMount` since it handles cases where render gets called twice - https://reactjs.org/docs/react-component.html#componentdidmount

But in this chapter (and other instances in the tutorial) we only call `setState` asynchronously in `componentDidMount`. So we shouldn't run into a performance issue.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-load-the-state-from-the-session/55

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-load-the-state-from-the-session/157
