### ISSUE TITLE
Comments: Clear the Session on Logout

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#41]
Link to chapter - http://serverless-stack.com/chapters/clear-the-session-on-logout.html

**Comment by dbeja** [comment]
I'm logging in with Facebook using the federated user pool.
Do you know how do I clear the session for this pool?

Thanks

**Comment by jayair** [comment]
@dbeja I'm not entirely sure which pool you are talking about. By federated user pool do you mean federated identities?

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-clear-the-session-on-logout/70
