### ISSUE TITLE
Docs: wrong link to github repo

### ISSUE THREAD

**Issue by patotoma** [AnomalyInnovations/serverless-stack-com#414]
Hey guys,

just wanted to let you know that in https://serverless-stack.com/chapters/redirect-on-login.html

at the bottom, there is a wrong link to GitHub repo. It should point to the frontend source instead of the backend source.

Currently: https://github.com/AnomalyInnovations/serverless-stack-demo-api/tree/redirect-on-login (which doesn't exist)
Expected: https://github.com/AnomalyInnovations/serverless-stack-demo-client/tree/redirect-on-login

I would open a PR but I couldn't locate the checkpoint text in the sources here.

Cheers! 🍻

**Comment by jayair** [comment]
Thank you for pointing it out! Fixed.

https://github.com/AnomalyInnovations/serverless-stack-com/commit/a74ef5b82d14c8bdf7338b5c0730591e68745da9
