### ISSUE TITLE
Comments: Give Feedback While Logging In

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#43]
Link to chapter - http://serverless-stack.com/chapters/give-feedback-while-logging-in.html

**Comment by jayair** [comment]
@staskh You could but in this case, we end up redirecting after the login is successful. So we don't have to explicitly handle it.

**Comment by verdavaine** [comment]
That's right but when you logout, your Login button is still in Loading state, before submitting the form.

**Comment by jayair** [comment]
@verdavaine Not quite, React Router unloads our Login container completely. So when it is brought up the next time it starts with the default state.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-give-feedback-while-logging-in/46

**Comment by tickcode** [comment]
For some reason the LoaderButton is not showing the spinning glyph.  I've gone back over the tutorial a number of times to make sure there wasn't a typo.  Is anyone else having this issue?  (Using Chrome)

**Comment by tickcode** [comment]
Sorry, false alarm here.  I missed "isLoading={this.state.isLoading}" in the <LoaderButton> tag of Login.js
