### ISSUE TITLE
Comments: Create the Signup Form

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#45]
Link to chapter - http://serverless-stack.com/chapters/create-the-signup-form.html

**Comment by hotsun** [comment]
if I open the signup link in another browser (without any session and cookies), it will return 404

**Comment by jayair** [comment]
@hotsun Can I see the full url that you are trying to hit?

**Comment by JohnTigue** [comment]
Excellent work on this tutorial. Really, a classic. 

I made it all the way to this chapter before any hiccups, and admittedly this is a small one. The follow is where things went ever so slightly wrong:
>Now if we switch to our browser and navigate to the signup page we should see our newly created form. Try filling it in and ensure that it shows the confirmation code form as well.

There is no `123456` and I don't see from the code how there could but this is my first React experience so what do I know. 

Nonetheless, I ignored the above and moved on to the next chapter without any problems.

**Comment by jayair** [comment]
@JohnTigue Ah, I see what you mean. Yeah it's not very clear from the instructions there. But you as a user, can ensure that the form sorta "works" by filling out the fields and typing in a confirmation code (in the screenshot I used `123456`) and hitting enter.

**Comment by walshe** [comment]
i thought amplify was going to handle all the forms ?

**Comment by jayair** [comment]
@walshe We are using Amplify to handle the actual sign up portion. If we were to use their forms, it would make it hard for people to swap it out and use their own authentication provider.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-the-signup-form/52
