### ISSUE TITLE
Comments: Signup with AWS Cognito

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#46]
Link to chapter - http://serverless-stack.com/chapters/signup-with-aws-cognito.html

**Comment by DushyantShukla** [comment]
Is this code functional? As I was able to register a new user. I found that The email attribute should be passed against the key email in the userAttributes parameter of [SignUp](http://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html) API.  Finally, below is my updated signup() method which works just fine:
`signup(email, password) {
        const userPool = new CognitoUserPool({
            UserPoolId: config.cognito.USER_POOL_ID,
            ClientId: config.cognito.APP_CLIENT_ID
        });
        const attributeList = [];
        attributeList.push(new CognitoUserAttribute({
            Name: 'email',
            Value: email
        }));
        return new Promise((resolve, reject) =>
            userPool.signUp(email, password, attributeList, null, (err, result) => {
                if (err) {
                    reject(err);
                    return;
                }
                resolve(result.user);
            })
        );
    }`

**Comment by jayair** [comment]
@DushyantShukla Yeah it is functional. The tutorial has been updated so that the `email` can be passed in as the username. You can read more about the update here - https://github.com/AnomalyInnovations/serverless-stack-com/issues/123.

If you need to reference the old version of the tutorial, there is a hosted version here - https://59a70f2ccf321c2ccb15113f--serverless-stack.netlify.com.

**Comment by DushyantShukla** [comment]
Oops! Didn't know that! I appreciate the response. Thanks!

**Comment by samxi** [comment]
I noticed that the verification code comes from noreply@verificationemail.com. Where is this address set? Not seeing it in the code so I'm guessing in AWS somewhere?

**Comment by QuantumInformation** [comment]
When a user signs up I get this screen

![image](https://user-images.githubusercontent.com/216566/31315194-532f84ee-ac0b-11e7-8396-3adbbdb741d5.png)

But I get an email link instead:

![image](https://user-images.githubusercontent.com/216566/31315209-8c26dd9c-ac0b-11e7-833c-4d99c2f9cbd6.png)

which takes me to this page

![image](https://user-images.githubusercontent.com/216566/31315211-962e8290-ac0b-11e7-8303-69bc093e1426.png)

**Comment by QuantumInformation** [comment]
I rechecked my pool with the advice in https://serverless-stack.com/chapters/create-a-cognito-user-pool.html but it seems the same to me.

**Comment by jayair** [comment]
Hmm can you check this setting?

<img width="1024" alt="screen shot 2017-10-09 at 7 06 20 pm copy" src="https://user-images.githubusercontent.com/53023/31362215-51c8cb18-ad25-11e7-88fe-4002329a67d3.png">

It should have defaulted to **Code** instead of **Link**.

**Comment by elnbado** [comment]
In   handleSubmit = async event =>

I get the following Warning when calling: 
  this.setState({
        newUser: newUser
          });

Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the Signup component.

Anyone else has this problem? Any ideas to resolve this?

**Comment by jayair** [comment]
@elnbado This happens usually when you make the `setState` call after you move away from the page. Is your app redirecting after you hit the Signup button?

**Comment by millergd** [comment]
For some reason, my signup() method did not work until I added an attribute list to the userPool.signUp() call. Is this out of date?

this is what my working code looks like:
`signup(email, password) {
        const userPool = new CognitoUserPool({
            UserPoolId: config.cognito.USER_POOL_ID,
            ClientId: config.cognito.APP_CLIENT_ID
        });
        const attributeList = [];
        attributeList.push(new CognitoUserAttribute({
            Name: 'email',
            Value: email
        }));
        return new Promise((resolve, reject) =>
            userPool.signUp(email, password, attributeList, null, (err, result) => {
                if (err) {
                    reject(err);
                    return;
                }
                resolve(result.user);
            })
        );
    }`

**Comment by jayair** [comment]
@millergd The tutorial had been updated a while back to set the email as the username in the User Pool. This makes it so that you don't have to set the attribute. You can read more about it here - https://github.com/AnomalyInnovations/serverless-stack-com/issues/123.

**Comment by millergd** [comment]
@jayair yeah it looks like I was using an older version of the tutorial and setting up the userpool different.

However, I don't really understand the changes. Can you clarify what was the norm before and after the update? 
```
Previously, we were **manually setting using the email as a user’s username**. There is one major issue with this; the username cannot be changed in your Cognito User Pool. AWS fixed this by adding the option of **using the email as the username** while logging in and signing up. 
```

**Comment by jayair** [comment]
@millergd Yeah the issue with setting the email as the username manually (as we were doing before) was that the username in Cognito cannot be changed. So you would need to work around this in case your users need to change their email.

But with the new email as username setting that's been introduced recently, the User Pool sets a unique string as the username internally. This allows you to change a user's email (and username) easily.

Hopefully that makes sense. It is a bit confusing though.

**Comment by akolybelnikov** [comment]
I'm running into a weird compilation error:
```
./src/containers/node_modules/amazon-cognito-identity-js/es/AuthenticationHelper.js
  Line 20:  Import in body of module; reorder to top  import/first
  Line 22:  Import in body of module; reorder to top  import/first

Search for the keywords to learn more about each error.
```
Has anyone else encountered that while using amazon-cognito-identity-js in a CRA project?

**Comment by d0ruk** [comment]
@jayair 

> setting the email as the username manually 

Can you elaborate on this? Did you use to derive a dummy username from the email?

I am using aws-amplify for Auth. Signature of the [signUp function](https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts#L100) is

> signUp(username: string, password: string, email: string, phone_number: string): Promise<any>

I *have to* supply a username. So I derive a username from the email, and do ```signUp(dummyName, password, email)```. However, this way, the user gets a username she doesn't even see. It's some specific way of string manipulation my client does.

Thus, when the user logs in via her email, that same util function derives the same username, and makes the request to the user pool with that. So the e-mail is really not needed, the way I went about doing it.

Did you have to do it like the above? Make up a username?

p.s. From the looks of [this PR](https://github.com/aws/aws-amplify/pull/79/commits/379ee152863800ced366fdd58f72ee607445715a), the new signature will be;

> signUp(username: string, password: string, email: string|Array<Object>, phone_number: string): Promise<any>

I think that will allow you to attach custom attributes to your user. However, that still seems to necessitate a username.

**Comment by jayair** [comment]
@d0ruk We were setting the username manually. As in passing in the email as the username. The error you are getting is because you have the email as alias option enabled. This means users can login with either their username or email. But it does not allow usernames that are of the email format since you could have an unverified email as the username. In the tutorial we don't use this option.

**Comment by d0ruk** [comment]
@jayair 

Thus, if I don't use any aliases, would the user pool accept signup/login flows with an email? As I linked above, the signUp() method requires a username.

I'm asking this because there might not be such an option in the aws-amplify API, yet. Cognito might be supportting it, however. I'm trying to discern what is possible with aws-amplify.

**Comment by jayair** [comment]
@d0ruk Yeah I'm not sure about amplify. Are you not able to change the User Pool settings from the AWS Console?

**Comment by d0ruk** [comment]
@jayair 

I'm trying to figure out the .yaml representation of the userpool in the tutorial. That's outside the scope of the book.

I'll leave it as is (derive username for login/verify) since it works. I'll note it somewhere here in case this turns out to be a no-no with aws-amplify.

Cheers.

**Comment by PraneshBalekai** [comment]
Is there a link/reference to how to register the user with an Identity pool after sign up?

**Comment by jayair** [comment]
@PraneshBalekai What do you mean by registering a user with an Identity Pool?

**Comment by PraneshBalekai** [comment]
I want to use Federated Identities in Cognito. I already created an identity pool and added my cognito user pool as an authentication provider. However, it does not automatically register as a new identity when I call confirmRegistration or authenticateUser. I tried to follow the method as given in use case 4 of   https://github.com/aws/amazon-cognito-identity-js and tried to refresh but it doesn't work (error: missing region in config, although it was all configured). Federated Identities was not covered in this tutorial but I was wondering if there is a guide or reference to managing federated identities in a reactJS app

**Comment by jayair** [comment]
@PraneshBalekai We do use Federated Identities in this tutorial. We call `confirmRegistration` right here - https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/src/containers/Signup.js#L106.

It sounds like you are getting an error because it wasn't configured properly.

**Comment by navinc** [comment]
Forgot Password use-case in Login/SignUp (or for 'extra credit') would be awesome!

**Comment by jayawics** [comment]
Hi @jayair - I actually went through the full tutorial and got to end but only tested using my own login created through the CLI. Upon further testing, I realized that users get an error when trying to Sign Up. I don't see anything wrong with my Signup.js file but when I enter an email/password and click the "Signup" button, the "Signing up..." loader keeps spinning and I get a "[object Object] error from the browser. I also get a "POST https://cognito-idp.us-east-1.amazonaws.com/ 400 ()" error in the Console. 
Have you ever encountered this issue or do you know what might be wrong? Thanks so much for the help!

**Comment by grundmanise** [comment]
Is there a specific reason why throughout the guide we create `new CognitoUserPool` on each function invocation in this and other similar functions:
```
signup(email, password) {
  const userPool = new CognitoUserPool({
    UserPoolId: config.cognito.USER_POOL_ID,
    ClientId: config.cognito.APP_CLIENT_ID
  });
 ...
}
```
IMHO it's better to create a `CognitoUserPool` once and use the exported `const`. For example I did it in the `awsLib.js`:
```
const userPool = new CognitoUserPool({
    UserPoolId: config.cognito.USER_POOL_ID,
    ClientId:   config.cognito.APP_CLIENT_ID,
});
export default userPool;
```

**Comment by jayair** [comment]
@grundmanise In this case we create one on every click. But yeah you could make it a part of some common code.

**Comment by viccooper142** [comment]
Hi Jayair, I'm getting a couple of errors I can't figure out. When my app page loads I get a "No userPool" alert. I can login as my test user just fine but then if I switch to a new page such as http://localhost:3000/notes/new (I just finished building this per Add the Create Note Page) then I get the same message. Also it appears that I am logged out. Any idea what I might have missed? Thanks!

**Comment by EllaVader** [comment]
When I try to sign up and recieve my confirmation code and then enter it in I get a message saying that "Auth.confirmSIgnup is not a function" . Here i screenshot and here is my code:

`handleConfirmationSubmit = async event => {
    event.preventDefault();
    this.setState({ isLoading: true });
    try{
      await Auth.confirmSignup(this.state.email, this.state.confirmationCode);
      await Auth.signIn(this.state.email, this.state.password);

      this.props.userHasAuthenticated(true);
      this.props.history.push('/');

    } catch (e) {
      alert(e.message);
      this.setState({isLoading: false});
    }
  }`


![notafunction](https://user-images.githubusercontent.com/8941982/38472876-88fdaa96-3b54-11e8-97a1-3c85db3346c7.png)

**Comment by jayair** [comment]
@EllaVader There is a tiny typo. It is `Auth.confirmSignUp`.

**Comment by jayair** [comment]
@viccooper142 Can you check this specific line in your `src/index.js` https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/configure-aws-amplify/src/index.js#L12?

It looks like Amplify might be trying to create an anonymous user every time you load your page.

**Comment by jayair** [comment]
@viccooper142 I think it's the order of the calls. Can you try moving the Amplify block below the imports and see if that fixes the issue?

**Comment by viccooper142** [comment]
@jayair  That worked! It was just the order. I copied your version of src/index.js and the error went away. Thanks!

**Comment by EllaVader** [comment]
@jayair thank you -- I missed that typo

**Comment by Tayl0rFay** [comment]
Although I copied and pasted the exact code from the Signup.js in the repo, for some reason the redirect isn't working right. 
1. I sign up
2. Enter the confirmation code
3. I get an alert saying "undefined"
4. I'm logged in, but I'm not redirected from the confirmation page.

<img width="1421" alt="screen shot 2018-04-21 at 8 42 19 pm" src="https://user-images.githubusercontent.com/22434607/39090149-f42eb7f6-45a4-11e8-9ebd-23645dd77254.png">

**Comment by jayair** [comment]
@Tayl0rFay Couple of things. Can you double check that the signup actually worked by trying to login with the credentials (make sure you are logged out first)? And can you post your `package.json` here as well?

**Comment by Tayl0rFay** [comment]
@jayair Yep, I'm able to sign in

```
{
  "name": "notes-app-client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "amazon-cognito-identity-js": "^2.0.3",
    "aws-amplify": "^0.3.0",
    "react": "^16.3.2",
    "react-bootstrap": "^0.32.1",
    "react-dom": "^16.3.2",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```

**Comment by jayair** [comment]
@Tayl0rFay One issue I see is the `amazon-cognito-identity-js` include. Compare it to the one we have in the tutorial - https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/package.json.

This might from an older version of the tutorial. I'm not sure if it's causing the problem but you can try removing it using `npm uninstall`.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-signup-with-aws-cognito/130
