### ISSUE TITLE
This seems strange? Is it possible to do this using React Context? 

### ISSUE THREAD

**Issue by stcalica** [AnomalyInnovations/serverless-stack-com#466]
https://serverless-stack.com/chapters/add-the-session-to-the-state.html 

I don't think I've seen something like this below. Seems like we are hacking react-router too much, as I can't find a similar pattern in their own docs. 
Was this created to make the available functions easier for the tutorial? 
Or is this literally the best practice for holding these functions in session state?

**Comment by jayair** [comment]
These steps were from 3 years ago. They've been recently updated.
