### ISSUE TITLE
Question on serverless-stack-demo-ext-api repo

### ISSUE THREAD

**Issue by Paul4912** [AnomalyInnovations/serverless-stack-com#480]
Hi, I have a questions regarding the extended serverless stack api repo. I posted it there but was told i should probably ask here.
Heres link to question
https://github.com/AnomalyInnovations/serverless-stack-demo-ext-api/issues/9

**Comment by jayair** [comment]
Hmm is the issue with the serverless-offline plugin? I meant maybe posting it over of their forums. Sorry for the confusion.
