### ISSUE TITLE
Comments: Upload a File to S3

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#49]
Link to chapter - http://serverless-stack.com/chapters/upload-a-file-to-s3.html

**Comment by geirman** [comment]
I'm getting this error back. I've searched my code for 'us-east-1' and find zero results. I've converted all those instances to 'us-east-2' to match values I got back from aws. Not too sure where to go from here at the moment. 

```
<Error>
    <Code>AuthorizationHeaderMalformed</Code>
    <Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-1'</Message>
    <Region>us-west-1</Region>
    <RequestId>39E99C1D42C6E600</RequestId>
    <HostId>tfuC/uhW4xhxPwMW+kqicWQxCdTznTrsYpM+lr40QGIyriIFysywMKlnnKqOGIKQ88SqN7SxWxE=</HostId>
</Error>
```

**Comment by jayair** [comment]
@geirman still having this issue? I noticed you commented on the Delete Note chapter.

**Comment by geirman** [comment]
Yes, it has something to do with the S3 upload. It works, but I get the error each time I attach something. No error when I just update the comment.

**Comment by jayair** [comment]
You get the error every time you create a new note with a file as an attachment? But the file is uploaded successfully? That's strange.

Where are you seeing this error?

```xml
<Error>
    <Code>AuthorizationHeaderMalformed</Code>
    <Message>The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-1'</Message>
    <Region>us-west-1</Region>
    <RequestId>39E99C1D42C6E600</RequestId>
    <HostId>tfuC/uhW4xhxPwMW+kqicWQxCdTznTrsYpM+lr40QGIyriIFysywMKlnnKqOGIKQ88SqN7SxWxE=</HostId>
</Error>
```

**Comment by geirman** [comment]
Everytime I create or update a note with and attach something. It's successfully uploaded though, which I agree seems strange. So it's not gating me. Would be nice to understand why it's happening though. 

I found the error under Networking > XHR > click on the item with a 400 error `?max-keys=0` > Preview > then expand the Error node. 

![2017-04-15_2330](https://cloud.githubusercontent.com/assets/1640318/25069354/dae1cad0-2233-11e7-95f4-b7c4e278adb6.png)

**Comment by jayair** [comment]
I played around with your app. I think I know what's going on. The AWS JS SDK has a region set to `us-east-1` but your S3 file uploads bucket is in `us-west-1`. Apparently, the SDK retries with the correct region, hence it ends up working. You can set the correct region before you do the upload by doing so.

```js
  const s3 = new AWS.S3({
    region: 'us-west-1',
    params: {
      Bucket: config.s3.BUCKET,
    }
  });
```

The tutorial doesn't need to do this because region set for the AWS JS SDK using the `AWS.config.update({ region: config.cognito.REGION });` call is the same for the S3 file uploads bucket.

You can read more about here - https://github.com/aws/aws-sdk-js/issues/986#issuecomment-217017283

**Comment by geirman** [comment]
Thanks @jayair, you've been a huge help. Setting the region to 'us-west-1' does resolve the problem, but I can't for the life of me figure out how that makes any sense. Everything I'm seeing indicates that the region should be 'us-east-2'. I tried it for giggles, but it errored as well. 

![2017-04-17_1113](https://cloud.githubusercontent.com/assets/1640318/25100949/16996c16-2367-11e7-8913-2404fc18f406.png)

**Comment by jayair** [comment]
What about the bucket that you set up for file uploads? The one we do in this chapter - http://serverless-stack.com/chapters/create-an-s3-bucket-for-file-uploads.html

**Comment by geirman** [comment]
That's the one

**Comment by jayair** [comment]
Thanks.

I don't think the region in the URL for the AWS Console is the region of the bucket. The console does show the correct region either in the list of buckets or in the bucket page. You can see it here in this screenshot.

![select-created-s3-bucket](https://cloud.githubusercontent.com/assets/53023/25144087/acde75ee-243a-11e7-9251-83df0d0dc38c.png)

And here is the US East (N. Virginia) - `us-east-1` mapping http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by nerdguru** [comment]
I'm getting a 403 on the PUT and rechecked my CORS settings on the bucket, which look OK.  What else should I be looking at to troubleshoot here?

**Comment by geirman** [comment]
@jayair Good call! The region thing seems like an important detail to AWS, but it gets in the way from my perspective. I wish we could abstract it away. 

![image](https://cloud.githubusercontent.com/assets/1640318/25242445/7f999986-25ae-11e7-9bd1-d0eaa55dd39f.png)

I created a codestar project this morning and as I was checking it out, I went back to my aws console and navigated back to it... and it was gone! I was confused, so I created another. Both seemed to work, so I kept scratching my head and figured out that my demo 1 was in a different region. Not sure why I switched regions, but it's a confusing detail that I continually seem to stumble on. (sorry to get off topic)

![image](https://cloud.githubusercontent.com/assets/1640318/25242596/112bfb8c-25af-11e7-8809-89a765494d7c.png)

**Comment by jayair** [comment]
@nerdguru can I see the full error? I think you can expand the 403 error in the console and it might give you some info on why it's failing. Also, let's see what the url endpoint is for the PUT request.

@geirman yeah in future we might look into building something that would hopefully abstract out these details and gotchas. If you come across some ideas, send them our way 😉

**Comment by nerdguru** [comment]
@jayair Here's what gets output in the Chrome console:

pete-notes-app.s3.amazonaws.com/us-east-1%3A636ea0f9-5d92-41f2-86eb-93aa67b66968-1492639359454-addams.txt:1 PUT https://pete-notes-app.s3.amazonaws.com/us-east-1%3A636ea0f9-5d92-41f2-86eb-93aa67b66968-1492639359454-addams.txt 403 (Forbidden)

That path looks right to me, but you're eyes might reveal something

**Comment by abagasra98** [comment]
@nerdguru I had the same problem. AWS throws a 403 error because the user permissions associated with the authorized users (of your identity pool) does not grant them access to read/write S3 data. 

The solution is to go into the IAM console, go to **Roles** tab on the side, click on the one associated with your Identity pool. For reference, mine was called "_Cognito_notesidentitypoolAuth_Role_" After you're on the **Summary** page, click _attach policy_ and choose the following: **AmazonS3FullAccess**

**Comment by fwang** [comment]
@abagasra98 is correct in that lack of S3 upload permission can cause the 403 error. Granting the identity pool with **AmazonS3FullAccess** solves the problem, but it also grants a user access to edit/remove files uploaded by other users. A very subtle tweak to the solution is to grant users edit/remove access only to files they uploaded.

@nerdguru Let's first take a look at the IAM policies assigned to the identity pool. As @abagasra98 suggested, go to **IAM console**, click on **Roles** in the left menu, click on **Cognito_notesidentitypoolAuth_Role**, click on **Show Policy** near the bottom of the page.

**Comment by nerdguru** [comment]
@abagasra98 and @fwang, that was it, thanks so much.  I clearly missed that step when setting up the Identity Pool.  I changed that policy to the one shown on that step and now it works like a champ.  My .txt file I selected in the app shows up with the expected prefixed name in my bucket.

Sorry it took me so long to find the quiet time to try it out 8)

**Comment by alpiepho** [comment]
@jayair add the Amazons3FullAccess policy allows me to upload files now.  Two questions:
1) I didn't follow comment from @fwang.  Is there a way to tighten that access?  (details would be appreciated)
2) did I miss a step in the tutorial?

Thanks for all the help here.

**Comment by fwang** [comment]
@alpiepho the policy allowing the Identity Pool to access S3 resources was defined in [Create a Cognito Identity Pool](http://serverless-stack.com/chapters/create-a-cognito-identity-pool.html) chapter. When the Identity Pool was first created, we attached the following policy:
```
{
  "Version": "2012-10-17",
  "Statement": [
  ...,
    {
      "Effect": "Allow",
      "Action": [
        "s3:*"
      ],
      "Resource": [
        "arn:aws:s3:::YOUR_S3_UPLOADS_BUCKET_NAME/${cognito-identity.amazonaws.com:sub}*"
      ]
    }
  ]
}
```
This grants access to ```YOUR_S3_UPLOADS_BUCKET_NAME``` bucket, and files prefixed with the users' identity in the bucket.

**Comment by hutualive** [comment]
why
"const uploadedFilename = (this.file)
 ? (await s3Upload(this.file, this.props.userToken)).Location
 : null;"
return an URL ?

in s3Upload, the returned object just have:
"return s3.upload({
    Key: filename,
    Body: file,
    ContentType: file.type,
    ACL: 'public-read',
  }).promise();"

I do not see the key word like "Location".

thanks.

**Comment by hutualive** [comment]
anyone has similar issue when upload the attachment to s3?

the api is working as without attachment, I can see the post result from aws console of DynamoDB.
I can upload a file to the s3 bucket with aws console too.

in the beginning, I'm thinking it's due to the network latency or firewall, but even tried with proxy the same alert message.

<img width="1245" alt="s3-upload-networking-failure" src="https://user-images.githubusercontent.com/527337/28856994-c8d94b7a-7778-11e7-934f-18954d16b464.png">

**Comment by hutualive** [comment]
when upload the attachment to s3, return "AccessDenied: Access Dennied" alert message.
anyone has similar issue?

the region is ap-northeast-1
my IAM gave AministratorAccess
the API alone is working properly but with attachment failed

thanks

<img width="1229" alt="access-denied-s3-upload" src="https://user-images.githubusercontent.com/527337/28861953-d1c7b4ca-7795-11e7-81b4-def326178325.png">

**Comment by jayair** [comment]
@hutualive This the AWS SDK docs for the `upload` method - http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property. It returns the `Location` property that we use. Our own `s3Upload` method is simply returning a Promise that eventually will give us the object containing the `Location` property.

**Comment by michaelcuneo** [comment]
I have an odd problem... my DynamoDB Tables and S3 File upload appear to be actually updating, if I log in to AWS console and look in the S3 Bucket, and the DynamoDB table, I'm actually getting proper data... but after a call, the Creating just spins and spins and spins... eventually I get these errors in my console.

PUT https://hrs-notes-uploads.s3-ap-southeast-2.amazonaws.com/undefined-1502368754577-IMG_0454.jpg net::ERR_CONNECTION_ABORTED
hrs-notes-uploads.s3-ap-southeast-2.amazonaws.com/?max-keys=0:1 GET https://hrs-notes-uploads.s3-ap-southeast-2.amazonaws.com/?max-keys=0 403 (Forbidden)
xhr.js?28e2:81 PUT https://hrs-notes-uploads.s3-ap-southeast-2.amazonaws.com/undefined-1502368754577-IMG_0454.jpg 403 (Forbidden)

No idea what I've done wrong.

**Comment by michaelcuneo** [comment]
Now I've got a new error with seemingly no changes whatsoever. :o 

POST https://5qyf9lxnte.execute-api.ap-southeast-2.amazonaws.com/prod/notes 403 ()
notes:1 Fetch API cannot load https://5qyf9lxnte.execute-api.ap-southeast-2.amazonaws.com/prod/notes. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.0.10:3000' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by michaelcuneo** [comment]
Disregard all that, I did a stupid thing. Circularly tried to push /notes ... N.B. don't do that. :)

**Comment by jayair** [comment]
@michaelcuneo Glad you figured it out.

**Comment by designpressure** [comment]
@fwang I've the same 403 error. I've verified my IAM roles policy and it is exactly as requested but I still have the problem.... what should I check?

**Comment by jayair** [comment]
@designpressure That CORS block that you posted is the default one. The one we use in the tutorial (https://serverless-stack.com/chapters/create-an-s3-bucket-for-file-uploads.html) looks like this:

``` xml
<CORSConfiguration>
	<CORSRule>
		<AllowedOrigin>*</AllowedOrigin>
		<AllowedMethod>GET</AllowedMethod>
		<AllowedMethod>PUT</AllowedMethod>
		<AllowedMethod>POST</AllowedMethod>
		<AllowedMethod>HEAD</AllowedMethod>
		<MaxAgeSeconds>3000</MaxAgeSeconds>
		<AllowedHeader>*</AllowedHeader>
	</CORSRule>
</CORSConfiguration>
```

Not sure if you missed it but give that a try.

**Comment by designpressure** [comment]
Yeah, that was the problem, now it uploads fine, thanks.

**Comment by QuantumInformation** [comment]
Note if you get an error that says AccessDenied, your police for the auth role is likely incorrect, for me it was the wrong bucket setting.

**Comment by tommedema** [comment]
Talking about security and validation: currently the size based validation is only running on the frontend:

```if (this.file && this.file.size > config.MAX_ATTACHMENT_SIZE) {
    alert("Please pick a file smaller than 5MB");
    return;
  }```

Obviously this is not something we could rely upon. Is it possible to enforce this in the policy document for s3?

**Comment by jayair** [comment]
@tommedema Yeah we don't cover this in detail but I think we could. There is a way to limit this but not through the policy that you set in the AWS Console. Instead you've to generate a pre-signed with the `content-length-range` header.

**Comment by tommedema** [comment]
@jayair I don't understand. The headers would still be controlled by the client, and therefore cannot be trusted. The enforcement necessarily has to come from the server-side. Since we don't have a server, the only way (from my perspective) would be to define it in a policy document. Am I missing something?

**Comment by jayair** [comment]
@tommedema It does require an API on the backend to sign these headers. Here is one way AWS docs show this - https://aws.amazon.com/articles/browser-uploads-to-s3-using-html-post-forms/.

**Comment by eldadmel** [comment]
I have a problem when I try to create a note with a file. I always get "AccessDenied: Access Denied" alert.
I checked the IAM role and the CORS and I think they are current. Is there anything else I can check?

**Comment by jayair** [comment]
@eldadmel Can you see the full error in the browser console?

**Comment by SpencerGreene** [comment]
I'm also seeing "AccessDenied: AccessDenied" alert.
The browser console message is:
`Failed to load resource https://sg-serverless-stack-tutorial-01.s3.us-west-2.amazonaws.com/us-west-2%3A403eb53b-5dc4-47c2-9a61-340175902fd1-1513360210560-testfile.txt: the server responded with a status of 403 (Forbidden)`

It's not in the client afaik - I tried your client from the github repo and the error is the same.

**Comment by jayair** [comment]
@SpencerGreene Check the IAM role for your Identity Pool in this chapter - https://serverless-stack.com/chapters/create-a-cognito-identity-pool.html

We set the permissions for what a client can access.

**Comment by SpencerGreene** [comment]
@jayair Thanks - fixed!  It looked to my eye like it matched what was in that chapter, but I copy-pasted over what I had just to be sure, and sure enough it started working - so I must have fat-fingered something.  (Curious - does AWS remember the history of my IAM role, so I can forensically analyze what I did wrong?)

**Comment by SpencerGreene** [comment]
OK here's a question -- I'm trying to implement the delete attachment "exercise for the reader."  I see that the 'attachment' value stored in the database table is the full Location including the bucket name, whereas the deleteObject api wants the key in its own parameter.  Is there a recommended way to strip the bucket name off of the 'attachment'?  I can string-manipulate it, but that makes an assumption on the format of that string, which seems like bad practice.  I was looking for an AWS api call that would take the Location and return the Key, but I don't see such api.  

Another way would be to store the Key instead of the Location; or to add another field to the database and store both.  What would you recommend?

**Comment by jayair** [comment]
@SpencerGreene As an exercise, removing the key from the url is okay. But the proper practice would be to store the key and the url.

**Comment by picwell-mgeiser** [comment]
I'm getting a CORS error similar but not the same as others

I readacted the S3 bucket name:
new:1 Failed to load https://s3.amazonaws.com/-----.-----.----/us-east-1%3A4d25e339-bdc1-4c09-9c83-5b99893414ec-1514561788846-ecsv_10_2017%20%282%29.csv: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403.

I deleted and recopied the CORS configuration XML.  This is what I get in the AWS console
 AFTER I save and come back to the CORS config
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

The App does retry the upload 4 times I see from the Developer console.  The problem is the 403 CORS issue, however

I can Upload and delete this file to the S3 bucket directly from the console no issues (but this is CORES issue according to message)

Thoughts?

**Comment by picwell-mgeiser** [comment]
I this because we're running the App from localhost and submitting to AWS without the react app setting a 'Access-Control-Allow-Origin' header?

**Comment by jayair** [comment]
@picwell-mgeiser In this chapter - https://serverless-stack.com/chapters/create-a-cognito-identity-pool.html we give permissions to our users to upload to S3. It is in the section where we add the policy for our Identity Pool. Just make sure you have completed this step properly.

**Comment by picwell-mgeiser** [comment]
I checked and the permissions look correct.

If I go into the IAM - Roles Cognito_NotesAppPoolAuth_role and expand the Policy and click on S3, under Write, the PutObject Resource = **BucketName | string like | pickme-sandbox-reactapp-files, ObjectPath | string like | ${cognito-identity.amazonaws.com:sub}* **

Also, would the error specifically say CORS error if it were a role config error?

**Comment by jayair** [comment]
@picwell-mgeiser AWS doesn't make it easy to debug these. The main thing I would check is for typos in these. Make sure the bucket name is correct in the roles and while you are uploading them. And the region as well.

**Comment by danielkaczmarczyk** [comment]
I have the very same issue as @picwell-mgeiser does. Have tried all methods in this (and other) threads. I have used an Allow-Control-Origin-* chrome extension to omit the requirement by enabling cross-origin response sharing and it helps with the preflight authorization but doesn't fix the fact that I get the 301 result. The current error is Response for preflight has invalid HTTP status code 301.

**Comment by jayair** [comment]
@danielkaczmarczyk And does this happen just for file uploads? Or for other API calls as well?

**Comment by danielkaczmarczyk** [comment]
@jayair Only on file uploads. I try to send a file, first I get a 200 GET from s3 with all cors headers set correctly, and after that, the OPTIONS call gets 301'd, the very same way as @picwell-mgeiser has described.

**Comment by michaelcuneo** [comment]
I have a feeling that something has gone and changed on AWS end... my app worked up until about a month back and now all of a sudden it doesn’t, with zero changes on my end at all. The push to database works fine, push to S3 does not. Just like what everyone else is experiencing. I’ve been trying to track this down for ages.

**Comment by bharloe** [comment]
For what it's worth the push to S3 still works fine for my app which I haven't touched in months

**Comment by jayair** [comment]
@danielkaczmarczyk Can you go into the IAM section of your AWS Console and find the role that is being used? Here are some screenshots on how to do it.

[Image 1](https://d33wubrfki0l68.cloudfront.net/d3c8486a04f3baea259053ef45cdc09c3e4d9b0b/90cbc/assets/debugging/select-iam-service.png)
[Image 2](https://d33wubrfki0l68.cloudfront.net/fbc6e501d1350a7177a00cf593d0749d14c6e326/a5e6f/assets/debugging/select-iam-roles.png)
[Image 3](https://d33wubrfki0l68.cloudfront.net/e6c6dcb7f718ea01eaa48f5e74cd4c10b447140a/3ad7f/assets/debugging/select-notes-identity-pool-auth-role.png)
[Image 4](https://d33wubrfki0l68.cloudfront.net/a929943696a88b103965137a351079486f337d99/910b1/assets/debugging/expand-auth-role-policy.png)

**Comment by danielkaczmarczyk** [comment]
Here's my IAM policy for cognito

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents",
                "cognito-sync:*",
                "cognito-identity:*"
            ],
            "Resource": [
                "*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::notes-app-uploads-dan/${cognito-identity.amazonaws.com:sub}*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "execute-api:Invoke"
            ],
            "Resource": [
                "arn:aws:execute-api:us-east-2:*:lg7wxu2y8b/*"
            ]
        }
    ]
}`

**Comment by jayair** [comment]
@danielkaczmarczyk That looks good. Can you also check the permissions for your S3 bucket?

[Image](https://d33wubrfki0l68.cloudfront.net/c322c5878440689d29ac5f6eb328a57cfd05589c/dc328/assets/s3/select-s3-bucket-cors-configuration.png)

**Comment by danielkaczmarczyk** [comment]
here:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

```

**Comment by jayair** [comment]
@danielkaczmarczyk Yeah that looks okay too. I can try your repo out and see what I can find. Can you publish it?

**Comment by danielkaczmarczyk** [comment]
many thanks for the effort, @jayair ! Here's the [backend](https://github.com/danielkaczmarczyk/serverlessNotes) and here's the [client](https://github.com/danielkaczmarczyk/serverlessNotesClient) should you need it

**Comment by jayair** [comment]
@danielkaczmarczyk So I tried it out. I noticed that your bucket is in `us-east-2`. This isn't a problem but it needs a slight tweak to the code before we do the upload.

```js
  const s3 = new S3({
    region: 'us-east-2',
    params: {
      Bucket: config.s3.BUCKET
    }
  });
```

I created a new S3 bucket in `us-east-2` using the tutorial instructions. And used your code base and my credentials and the upload worked. But it still didn't work on your bucket.

I cannot check what the settings are on your bucket but can you try re-creating the bucket (and editing the IAM policy for Cognito with the new bucket)?

**Comment by danielkaczmarczyk** [comment]
I have created a new bucket, in us-east-2 (Ohio), amended `config.js` with the new value for `BUCKET`, amended the IAM policy for Cognito to make sure that I give it access to write to this particular bucket, and I get a 403 `Bucket not found` as if the authentication didn't work. No more error details present

**Comment by danielkaczmarczyk** [comment]
Ok, I have gone back & forth with different configurations and it has eventually worked. Not sure what exactly has made the difference, as upon inspecting the details it seems that all is as was during previous 'correct' versions. I blame that on human error - I may have mistyped something. The only takeaway that I'm sure of is that if the bucket was in `us-east-1`, which is N. Virginia, it always would `301`.

**Comment by jayair** [comment]
@danielkaczmarczyk Glad you figured it out. These can be tricky to debug!

**Comment by mbahfauz** [comment]
everyone know how to make our upload images become public read?

**Comment by jayair** [comment]
@mbahfauz There is a section in the Amplify Docs that might help with this - https://aws.github.io/aws-amplify/media/storage_guide#s3image

**Comment by mbahfauz** [comment]
Thanks man

**Comment by jayair** [comment]
@viccooper142 I think you might have missed a step in the previous chapter - https://serverless-stack.com/chapters/call-the-create-api.html

There we add the `createNote` method which in turn uses the `API` module. This will resolve both your issues.

**Comment by 19bharatvikram** [comment]
Hi Jay,

I have a <UnauthenticatedRoute ...> page where I want to display some public image from AWS S3 using <S3Image imgKey={temp.attachment}/> where  S3Image component is from 'aws-amplify-react'

I get error: cannot get guest credentials when mandatory signin enabled.

To solve it I used mandatorySignIn: false in my Amplify.configure  settings in index.js but I am still getting the below error.


StorageClass - ensure credentials error": NotAuthorizedException: Unauthenticated access is not supported for this identity pool.

Any insights will be appreciated. Please suggest if there is a way to load images for non authenticated users.

Thanks,
Bharat Chand

**Comment by jayair** [comment]
@19bharatvikram Yeah this setup is a bit different. You need to create an Unauth role for your Identity Pool to specify the resources unauthenticated users have access to.

**Comment by 19bharatvikram** [comment]
Thanks Jay, Enabling access to unauthenticated identities and giving readonly s3 permission to Unauthenticated role solved the issue.

![image](https://user-images.githubusercontent.com/31919585/39823964-d1713588-53cb-11e8-8d4d-8a3784891e38.png)

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-upload-a-file-to-s3/123
