### ISSUE TITLE
Can't create a new cognito test user

### ISSUE THREAD

**Issue by ytian90** [AnomalyInnovations/serverless-stack-com#5]
Hi,

I am trying to create a cognito test user as the steps below
http://serverless-stack.com/chapters/create-a-cognito-test-user.html

$ aws cognito-idp sign-up --client-id 4akg9bieef2upi103bk3o6sg9n --username admin@example.com --password PasswOrd!   --user-attributes Name=email,Value=admin@example.com

Error is 
Could not connect to the endpoint URL: "https://cognito-idp.None.amazonaws.com/"

Is there any config that I am missing?

Thanks,
Louis

**Comment by fwang** [comment]
Hi @ytian90,

Have you run `$ aws configure` to configure your AWS access keys and region. Double check and see if you have `config` and `credentials` files in your `~/.aws/` directory.

Follow this chapter if you have not set it up
http://serverless-stack.com/chapters/configure-the-aws-cli.html

**Comment by ytian90** [comment]
@fwang Thanks for the replying! I already set the configure, but I use the Default region name as "None", if I remove the region name, it asked me
You must specify a region. You can also configure your region by running "aws configure".
I am not sure which region name should I use in this case.

**Comment by fwang** [comment]
If you have created AWS resources like DynamoDB or Cognito User Pools, try use the same region here. If you have not created any resources through AWS console, you can use 'us-east-1' US East Virginia for now.

Your `~/.aws/config` should look like this after the region is set.
`
[default]
region = us-east-1
`

**Comment by ytian90** [comment]
@fwang It works!! Thanks a lot!

**Comment by fwang** [comment]
👍
