### ISSUE TITLE
#Hacktoberfest participation?

### ISSUE THREAD

**Issue by dorelljames** [AnomalyInnovations/serverless-stack-com#504]
Do you mind opting-in this great open-source reference participating in this month's #Hacktoberfest? 

Please see https://hacktoberfest.digitalocean.com/hacktoberfest-update

Basically, you'll just have to add topic to this repo `hacktoberfest` or add a label `hacktoberfest-accepted` to any PR's. Thank you

**Comment by jayair** [comment]
Oh hmm saw this way too late. Maybe next year!

**Comment by dorelljames** [comment]
Yeah sure. No problems. Thank you. 😊
