### ISSUE TITLE
Comments: List All the Notes

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#51]
Link to chapter - http://serverless-stack.com/chapters/list-all-the-notes.html

**Comment by nvallepalli** [comment]
cannot find the existing notes. 
![screenshot](https://user-images.githubusercontent.com/23063546/30754667-37b11b3a-9f89-11e7-8b22-c8d943b42cc1.PNG)

**Comment by nvallepalli** [comment]
and also invoking create API works for creating notes. But, not able to create a note through the web app.
I mean I cannot find data in dynamodb table which I tried to insert using the web app.

**Comment by jayair** [comment]
@nvallepalli So this chapter (https://serverless-stack.com/chapters/test-the-apis.html) worked for you. But you could not get it to work on the web? Can you check if the console is displaying any errors and if the request to create a note worked properly?

**Comment by nvallepalli** [comment]
yeah this chapter (https://serverless-stack.com/chapters/test-the-apis.html) worked for me, but i could not get it on web.

**Comment by jayair** [comment]
@nvallepalli Does the request to create the error succeed when you try it on the web?

**Comment by copperspeed** [comment]
How is `this.props.isAuthenticated` set? It's always undefined for me? I do have a token but when console.log `this.props`. `isAuthenticated is not there.

**Comment by jayair** [comment]
@copperspeed It's set in these chapters - https://serverless-stack.com/chapters/add-the-session-to-the-state.html & https://serverless-stack.com/chapters/load-the-state-from-the-session.html. It's pretty much right at the beginning.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-list-all-the-notes/63

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-list-all-the-notes/156
