### ISSUE TITLE
Comments: Render the Note Form

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#54]
Link to chapter - http://serverless-stack.com/chapters/render-the-note-form.html

**Comment by mikhaelbendavid** [comment]
When I click a note to examine, the page redirects to prod/notes/undefined - and I get an error.

I'm getting an error saying 
<img width="1204" alt="screen shot 2017-07-24 at 10 38 17 pm" src="https://user-images.githubusercontent.com/15205259/28608224-5c26c294-7194-11e7-97c0-d70635231cfa.png">

I've taken a look at the Notes.js file, the getNotes() is invokeApig at `/notes/${this.props.match.params.id}` If I'm not mistaken, it should be redirecting to the ID number for the note item, correct?

**Comment by RaphaelMui** [comment]
When I click one of my note, a status code 500 returned.

**Comment by jayair** [comment]
@RaphaelMui The 500 error should be something we are generating. Make sure the link for the note looks right. You can also check your CloudWatch logs for the error.

**Comment by RaphaelMui** [comment]
@jayair The Request URL is https://uy6essyal3.execute-api.us-east-1.amazonaws.com/prod/notes/9704e3b0-7d82-11e7-9f52-abe788a40b9a

From the CloudWatch logs, 

2017-08-10T08:13:34.778Z	cd8bc624-7da3-11e7-a4d5-bf4a01ad26b2	ReferenceError: error is not defined
at _callee$ (/var/task/get.js:199:27)
at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:65:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:303:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/var/task/node_modules/regenerator-runtime/runtime.js:117:21)
at step (/var/task/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
at /var/task/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by jayair** [comment]
@RaphaelMui Hmm that seems a bit cryptic. Can you try adding some debug message? For example, you can add a `console.log` before this line - https://github.com/AnomalyInnovations/serverless-stack-demo-api/blob/master/get.js#L27

**Comment by inventanew** [comment]
I'm getting this error...
./src/containers/Notes
Module build failed: Error: ENOENT: no such file or directory, open

**Comment by jayair** [comment]
@inventanew Seems like that file might not be in the right location?

**Comment by mdhendri** [comment]
With the demo app I am getting the following error "This XML file does not appear to have any style information associated with it. The document tree is shown below."  Why is this happening?  I am also seeing this with my local app.  It seems like the URL may be miss formed.

**Comment by jayair** [comment]
@mdhendri Which page of the demo app are you seeing this on - https://demo.serverless-stack.com?

**Comment by mdhendri** [comment]
Yes, the issue was on  https://demo.serverless-stack.com and also my own
app.  It seems that if there was an image in the S3 bucket prior to the
switch to AWS Amplify somehow the URL got messed up and hence the error.
If I uploaded another image then it seemed to resolve itself.  The
interesting thing is I tried it again this morning and I don't get that XML
error.

**Comment by iggirex** [comment]
How does wrapping JSX html code inside curly braces work? This line:
```
{this.state.note &&
        <form onSubmit={this.handleSubmit}>
```
Doesn't the && symbol make this a conditional statement? Wouldn't it just return a boolean? The instructions say "We render our form only when this.state.note is available." Is this the line that does that? How does && work here?

**Comment by jayair** [comment]
@iggirex Yeah JSX is a bit confusing. One way to think about it is that React converts JSX into a set of standard JS calls to create components. In this case, if `this.state.note` is not null (or false), it'll return the React component called `form`. If it's null then it won't render anything.

Here is some info on how `false` is rendered in JSX - https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-render-the-note-form/40

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-render-the-note-form/140
