### ISSUE TITLE
Comments: Create a Route That Redirects

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#58]
Link to chapter - http://serverless-stack.com/chapters/create-a-route-that-redirects.html

**Comment by rkmax** [comment]
For some reason when I redirect to AuthenticatedRoute show white (nothing) I have to refresh in order to see the content

`<AuthenticatedRoute exact={true} path="/" component={HomePage}/>`

**Comment by jayair** [comment]
@rkmax I guess you are setting it up a little differently from the tutorial. But what does your `HomePage` component look like?

**Comment by rkmax** [comment]
something like

```js
class HomePage extends React.Component {
  render() {
    return (
      <div className="container">{/* more stuff here */}</div>
    );
  }
}
// ...
export default connect(mapToPros, mapToActions)(HomePage);
```

**Comment by jayair** [comment]
@rkmax Are you using this with Redux?

**Comment by rkmax** [comment]
yes

**Comment by jayair** [comment]
@rkman I would need to play around with it to see how that would work out. But you can try to debug and see why the `render` method for your `HomePage` component is not getting called.

**Comment by Rickkwa** [comment]
lol you tagged the wrong person.

**Comment by DamickDoni** [comment]
Hi,

im using the auth routes with childProps 
`    <AuthenticatedRoute path="/test" exact component={test} props={childProps} />
    <AuthenticatedRoute path="/test/:number" exact component={numbertest} props={childProps} />`

When I want to use `  console.log("props", this.props.match.params.id);` in **numbertest** I get =>

> TypeError: Cannot read property 'params' of undefined

How can I get the URL parameter in e.g **componentDidMount()** ?
