### ISSUE TITLE
Comments: Use the Redirect Routes

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#59]
Link to chapter - http://serverless-stack.com/chapters/use-the-redirect-routes.html

**Comment by limifont** [comment]
<img width="487" alt="screen shot 2017-08-12 at 7 27 12 pm" src="https://user-images.githubusercontent.com/18182633/29245327-46825594-7f94-11e7-8dd4-110b4e80cde0.png">
This is what I'm getting instead of being redirected to the home page

**Comment by walshe** [comment]
If I want one or more special admin users of the app. How is the best way to handle this a) on the Cognito side and b) on the client side

Unsure if its IAM roles I should be using or the Groups facility in Cognito.

i.e. when a regular user signs up I would like them to have a 'APP_USER' role or something that I can also get from the currentUser variable on the frontend side (so that I can render correct menus etc)

I guess I could role my own sort of approach but surely theres some way of doing this with cognito ?

**Comment by jayair** [comment]
@walshe Yeah as I was saying in the other thread, I'm not sure if there is a built-in way to do this.

**Comment by DavidNaMills** [comment]
i'm getting the most insane result from this chapter:
I was testing the redirect function when everything went wrong.
Trying to access "localhost:3000/notes/new" when not logged in.
I get the following error message:
`Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

and the URL looks like this:
```
http://localhost:3000/notes/login?redirect=/notes/login%20?redirect=/notes/login%20?redirect=/notes/login%20?redirect=/notes/login%20?redirect=/notes/login%20?redirect=/notes/login%20?redirect=/notes/login%20?redirect=/notes/login%20?
(I deleted about 20 lines for the sake of length)
```

The error is pointing at:
```
G:/aws_tutorial/react_front/notes-app-client/src/App.js:33

> 33 |   this.setState({isAuthenticating:false});
```

Any ideas?

**Comment by walshe** [comment]
only call setState from somewhere that is handling an event

**Comment by jayair** [comment]
@DavidNaMills It looks like it caught in some sort of a loop, where it is redirecting back to itself?

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-use-the-redirect-routes/57

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-use-the-redirect-routes/152
