### ISSUE TITLE
Comments: Redirect on Login

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#60]
Link to chapter - http://serverless-stack.com/chapters/redirect-on-login.html

**Comment by johnkorzhuk** [comment]
A bug that I found: when there are multiple users. Logging into a different account with another user's redirect query string will throw an error. It's caused by these two bits of code:

In Notes.js
```
async componentDidMount () {
    try {
      const results = await this.getNote()

      this.setState({
        note: results,
        content: results.content
      })
    } catch (e) {
      alert(e)
    }
  }
```
and in get.js
```
try {
    const result = await dynamoDbLib.call('get', params)
    if (result.Item) {
      callback(null, success(result.Item))
    } else {
      callback(null, failure({ status: false, error: 'Item note found.' }))
    }
  } catch (e) {
    callback(null, failure({ status: false }))
  }
```

In Notes.js you're setting the state to the error object returned from get.js.

**Comment by johnkorzhuk** [comment]
My solution:
```
 async componentDidMount () {
    try {
      const results = await this.getNote()
      if (results.error) {
        this.props.history.push('/')
      } else {
        this.setState({
          note: results,
          content: results.content
        })
      }
    } catch (e) {
      console.error(e)
    }
  }
```
It works, but a network request is still send out.

**Comment by jayair** [comment]
@johnkorzhuk it's a good idea to send people to the homepage in that case. The tutorial is very light on error handling and we leave most of it up to you.

However, there is an issue in the way we are handling the API Gateway errors. It needs to trigger the try catch block instead of passing off as success. To do so, we need to throw an error in the `invokeApig` method in `libs/awsLib.js` when we encounter non-200 responses.

```js
if (results.status !== 200) {
   throw new Error(await results.text());
}
```

Thanks for pointing it out. Just updated it - aace17b1b44976229fb117a133fe428b4de4202a

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-redirect-on-login/24
