### ISSUE TITLE
Comments: Create an S3 Bucket

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#62]
Link to chapter - http://serverless-stack.com/chapters/create-an-s3-bucket.html

**Comment by bharloe** [comment]
Hi @jayair 
In most tutorial I've done using AWS to create serverless websites, I've had to name the s3 bucket identically to the domain I plan to point at it. So if I wanted to use "www.example.com" as my domain, the bucket in s3 would literally be named "www.example.com". Would you be able to explain how you avoided that in this tutorial?

**Comment by jayair** [comment]
@bharloe You need to use the same name if your domain in Route 53 is going to be pointing to your S3 bucket directly. In our case we use a CloudFront Distribution in front so you don't need to follow the naming convention.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-an-s3-bucket/48
