### ISSUE TITLE
Comments: Create a CloudFront Distribution

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#64]
Link to chapter - http://serverless-stack.com/chapters/create-a-cloudfront-distribution.html

**Comment by tommedema** [comment]
> So we are going to create a custom error response and return a 200 status code instead. The downside of this approach is that we are going to be returning 200 even for cases where we don’t have a route in our React Router. Unfortunately, there isn’t a way around this. This is because CloudFront or S3 are not aware of the routes in our React Router.

This seems like a deal-breaker for production / corporate purposes. Instead of saying there is no way around this, perhaps we should explore serverless alternatives to using cloudfront + S3?

For example, what about serving the application directly from Lambda with a simple node HTTP server?

**Comment by jayair** [comment]
@tommedema It depends what your client side app is for. If your app is a dashboard and the "routes" are purely for client side use then this isn't as much of an issue. However, if you are using it to serve content publicly then using a Create React App is probably not the best solution anyway.

Lambda + HTTP does work for cases but you need to decide if a cold start is okay for your use case.

For other ways to deploy your Create React App you can refer to - https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

**Comment by bharloe** [comment]
@jayair Could you explain why Create React App is not a good solution for serving content publicly? I can't really think of any deal breakers. Maybe it would be good to have a "use cases" page for this serverless stack?

**Comment by jayair** [comment]
@bharloe That's a good point. We cover a specific use case for building a client side app in React but we are noticing more folks extending the use cases.

For public content pages, SEO would be my biggest concern (even though Google does index client side JS). I would feel more comfortable using some sort of a static site generator (like [Gatsby](https://www.gatsbyjs.org) perhaps).

I'm not sure if these would classify as deal breakers for me. But as it was pointed out above, maybe the response headers for pages that are not found being displayed as 200s is one for you.

**Comment by tommedema** [comment]
@jayair Gatsby is a good recommendation. I'll give it a go.

**Comment by bharloe** [comment]
@jayair I see, yeah those are important considerations. As someone who was coming at this with more serverless experience and basically zero react experience these problems are news to me, and I would really appreciate a page that explains potential pitfalls like this somehow. But overall I love this tutorial (seriously, one of the best I've ever taken), and I know you have to draw the line somewhere as far as what this tutorial covers. Thanks for the Gatsby recommendation, I'll check it out. Is it fair to say that the issue, insofar as SEO concerns go, is that the app is built as bundled javascript which many web scrapers have trouble with parsing? So it's not necessarily an issue inherent to React, but rather to how the React app is built/deployed?

**Comment by jayair** [comment]
@bharloe Thanks!

Yeah the app we are creating in the tutorial is rendered completely on the client side. But React does support server side rendering as well. So when you request a URL it responds with the complete content as the HTML (as opposed to returning the bare minimum HTML and making API requests after). And I know Google does execute client side JS (I think Bing doesn't) and I wouldn't feel comfortable hosting a blog or a content driven public site with just client side rendering. That's not to say that people don't but I would prefer not to.

**Comment by maxdarque** [comment]
When I tried this on S3, I got a 403 response. Is it worth setting up Error page for a 403 response with a redirect to /index.html?

Same as this person https://medium.com/@omgwtfmarc/deploying-create-react-app-to-s3-or-cloudfront-48dae4ce0af

**Comment by jayair** [comment]
@maxdarque We do handle 404s in the demo app and return them as 200s. So [demo.serverless-stack.com/asd](https://demo.serverless-stack.com/asd) would return a 200 and React would display a message for us. Is that what you referring to?

**Comment by maxdarque** [comment]
@jayair Yes the demo app handles 404s. I set up the 404 Error redirect however for some reason S3 would return 403s when I would refresh a react-router page i.e. www.example.com/example-react-router-route. So to handle this I setup 403 redirects to /index.html.

**Comment by zamirkhan** [comment]
@jayair I've come quite far with the app that I built using this tutorial and it's been great so far. However, I've come to a point where server-side rendering is looking like a path I need to go down, since I need certain links from my app to be crawl-able by Facebook, for example. I've read about services like prerender.io or Netlify and also about things like Next.js or setting up a web-server for the "serverless" app. What path would you recommend to enable SSR for an application like this one?

**Comment by jayair** [comment]
@zamirkhan I think Next.js is a good option for SSR with React. The structure of their apps are a bit different but they have been consistently getting better.

**Comment by tommedema** [comment]
@jayair how do you compare Next.js with Gatsby?

**Comment by jayair** [comment]
@tommedema I think because of the original intentions of the projects, Gatsby is more for static content or structured dynamic content (like blogs). Whereas Next.js is a framework for building SSR React apps. But both the projects have evolved where there is quite a bit of overlap in the use cases.

For me personally; I'd use Gatsby for blogs and other CMS-style projects and Next.js for web apps where I need SSR.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-create-a-cloudfront-distribution/104
