### ISSUE TITLE
Comments: Set up Your Domain with CloudFront

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#65]
Link to chapter - http://serverless-stack.com/chapters/setup-your-domain-with-cloudfront.html

**Comment by jeffthefate** [comment]
I'm not sure if this was just because I had to move a domain from one AWS account to another, but my domain and hosted zone didn't have the same name servers. Once I synced those up, everything was magic.

**Comment by jayair** [comment]
@jeffthefate Thanks for leaving a note. I'm not sure if that's the issue but it might help some other folks.

**Comment by littleredshack** [comment]
Hmm.  When I start this section on Creating Hosted Zones I get the following screens:

![image](https://user-images.githubusercontent.com/11097799/33818713-90d27a10-de9a-11e7-9187-7c98f66312b5.png)

![image](https://user-images.githubusercontent.com/11097799/33818727-a4f54036-de9a-11e7-9bfd-215b3ab68602.png)

**Comment by jayair** [comment]
@littleredshack Thanks for the comment and the screenshots. I added a small note to the chapter about it.

**Comment by littleredshack** [comment]
Stuck on this one guys.  I have set DNS servers the same for domain and hosted zone as per comment above.  But when I try to open a browser to my domain I get:

![image](https://user-images.githubusercontent.com/11097799/33869190-93b4ba42-df5b-11e7-9437-443c9cf3374c.png)

Any ideas ?

**Comment by littleredshack** [comment]
Hmm.  Looks like it is my service provider DNS that has not updated:

![image](https://user-images.githubusercontent.com/11097799/33869305-18aa5e64-df5c-11e7-8e8f-58231557f70d.png)

**Comment by littleredshack** [comment]
Yup.  Fixed.  Changed my DNS server on my laptop to point to google DNS

**Comment by jayair** [comment]
@littleredshack Ooof glad you figured it out.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-set-up-your-domain-with-cloudfront/149
