### ISSUE TITLE
Comments: Set up SSL

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#67]
Link to chapter - http://serverless-stack.com/chapters/setup-ssl.html

**Comment by geirman** [comment]
![2017-04-16_0928](https://cloud.githubusercontent.com/assets/1640318/25072595/45bed7d2-2287-11e7-856b-516dfcd632c6.png)
I got this error, but maybe it's because I didn't actually purchase a domain. Instead, I used a domain I already own (at godaddy) and pointed to the AWS DNS servers. Find it here [kikitty.com](http://kikitty.com). Hoping I setup the www.kikitty.com bit properly. As of now, that's still not working.

**Comment by jayair** [comment]
@geirman it looks like the two links are working now?

At which step did you see this error?

**Comment by geirman** [comment]
It happened when I should have received this...
![](http://serverless-stack.com/assets/validation-for-domains.png)

**Comment by jayair** [comment]
Did you hit the limit on the number of certificates you can generate (http://docs.aws.amazon.com/acm/latest/userguide/acm-limits.html)?

If not then you might need to contact AWS.

**Comment by geirman** [comment]
I created an account to do your tutorial, so this was the very first certificate i tried to create. Unfortunately, tech support is "Unavailable under the Basic Support Plan"

**Comment by jayair** [comment]
Hmm that's really strange. It would be good if you could report back once they fix it for you. In case other folks run into similar issues.

**Comment by geirman** [comment]
It's fixed. I requested a "Service Limit Increase" as shown above and received this yesterday (17 hours ago)...

> I’m happy to inform you that we've approved and processed your Certificate Manager limit increase request for the US East (Northern Virginia) region. Please keep in mind that it can sometimes take up to 15 minutes for this to propagate and become available for use.

I waited 4 hours and tried again, but got no love. However, I tried again this morning and finally found success! Yay! 

They unfortunately offered no explanation as to why I needed to make this request at all.

**Comment by jayair** [comment]
Yeah their support can be a bit opaque at times.

**Comment by ryanjcruz** [comment]
I encountered an issue wherein the certificate created isn't showing up - for those having the same one, make sure that the region you are currently in is US EAST (N.Virginia). Turns out I was in US WEST (Oregon) when I created the certificate and it doesn't seem to propagate right away.

**Comment by henning** [comment]
Hello,
Thanks for the tutorial.

Looks interesting, but I want to avoid to configure services by clicking around a lot, IMHO things should be done with Infrasturcture as code. 

So I intend to solve this if possible by adding the proper cloudformation configs to my serverless.yml. Dou you think that's possible - and easy or hard?

**Comment by jayair** [comment]
@henning Some parts of the tutorial can be put into CloudFormation and `serverless.yml` but there are portions that are not supported by it. I know @nerdguru has been trying to figure that out as well.

And I agree, things should be automated but as a tutorial showing a bunch of CloudFormation templates isn't very instructive.

**Comment by mmiinnovations** [comment]
Great tutorial first off! Thanks for the fine work on it.

Everything worked great until this step. After I setup the SSL and changed the Cloudfront Distributions ' settings, I get ERR_TOO_MANY_REDIRECTS error.

**Comment by jayair** [comment]
@mmiinnovations Thank you!

Some of this redirect stuff is a bit confusing. You just need to make sure the redirects are set up the right way. Also because of the CloudFront cache, the changes can take a little bit of time to take effect.

Basically, it looks like:

```
http://domain -> https://domain
http://www.domain -> https://domain
https://www.domain -> https://domain
```

To do this our main CF needs the **Redirect HTTP to HTTPS** but we leave our www CF as **HTTP and HTTPS** for the **Viewer Protocol Policy**.

Let me know if your settings look like this.

**Comment by mmiinnovations** [comment]
Yes those are my settings. 

I found what's causing the error but how to fix it. When I set the S3 settings back to "Use this bucket to host a website" everything works fine. When it's set as the tutorial, I get "ERR_TOO_MANY_REDIRECTS" error. It's very consistent and repeatable.

Ideas?

**Comment by jayair** [comment]
@mmiinnovations You've got two S3 buckets right? One of them is hosting a site and the other is doing the redirect.

**Comment by mmiinnovations** [comment]
No. I'm very confused if that's what's required.

**Comment by jayair** [comment]
@mmiinnovations Yeah we need a second S3 bucket to handle the redirect for our www version of the domain. It's a part of this chapter - http://serverless-stack.com/chapters/setup-www-domain-redirect.html.

Here is a reason why we do a redirect instead of just pointing both the www and apex domain to the same CloudFront and S3 bucket - https://github.com/AnomalyInnovations/serverless-stack-com/issues/66#issuecomment-312728802

**Comment by mmiinnovations** [comment]
OK got it. After reading back through there I see it. I think that section of the tutorial needs just a bit more explanation. It's confusing and not explained well there.

Not complaining! You guys are great! This tutorial has been awesome. Thanks again for the work you put into it.

**Comment by jayair** [comment]
@mmiinnovations Yeah I'll add a bit more detail to it. Thanks for the feedback!

**Comment by hutualive** [comment]
@jayair 
two comments:
1.the certificate can be selected from the dropdown list of cloudfront, is only available to be created in us-east-1 region(N.Virginia), create from other region is not working.
2.for bare domain(example.com),suggest for the viewer policy to use redirect http to https, which is less confusing and better for the security purpose. because when we hitting www.example.com, will auto redirect to https://example.com, but when we hitting example.com, it will stay as is unless people specify https://example.com, which is not normal case.

thanks for your great tutorial : )

**Comment by jayair** [comment]
@hutualive good point on the certificate region issue. Added a note.

For the bare domain, we do ask people to redirect HTTP to HTTPS. It's one of the steps in the chapter.

**Comment by littleredshack** [comment]
There is a second step in AWS Certificate Manager to validate either via DNS or email:

![image](https://user-images.githubusercontent.com/11097799/33911785-8c63866a-dfe7-11e7-9fae-b036c963181f.png)

![image](https://user-images.githubusercontent.com/11097799/33911807-a6f2e868-dfe7-11e7-885e-2126ce6bf6c0.png)

**Comment by jayair** [comment]
@littleredshack Did you do the CNAME record in place of the email validation?

**Comment by littleredshack** [comment]
Yes. There was an option to allow AWS to update the DNS and I just clicked on that








Sent from Outlook Mobile







On Fri, Dec 15, 2017 at 12:01 PM -0500, "Jay V" <notifications@github.com> wrote:












@littleredshack Did you do the CNAME record in place of the email validation?

**Comment by jayair** [comment]
@littleredshack I see. Yeah we might cover that option in the future.

**Comment by BIWhitfield** [comment]
Hi guys, great tutorial! One of my only issues was that when I set up the validation in this section by email, it sent validation emails to 5 common email addresses associated with the domain I bought from Route 53. However I can't for the life of me work out how to access those emails to approve the validation. As far as I can tell the Route 53 domain doesn't support email forwarding and I can't find an inbox area to validate. I've ended up clearing out the validation by email and doing the DNS way. Just waiting on that to refresh (30 mins apparently) so I can finish the https part of that chapter. 

Any ideas where those emails go just for my own reference?

**Comment by jayair** [comment]
@BIWhitfield Honestly I'm not entirely sure. I think it goes to what Route53 thinks is associated with your domain?

We should change the tutorial to use the DNS way instead, it's far more reliable.

**Comment by alex-romanov** [comment]
I'm getting the ERR_TOO_MANY_REDIRECTS when trying to load the site, I already have the two s3 buckets (one to handle redirects) I've been going over all the steps to see if I'm missing anything but nothing stands out, is there a way to troubleshoot where the error is?

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-set-up-ssl/105

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-set-up-ssl/133
