### ISSUE TITLE
Comments: Deploy Again

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#70]
Link to chapter - http://serverless-stack.com/chapters/deploy-again.html

**Comment by geirman** [comment]
So for this section, I did something simple and pretty cool that I think would easily add value to this chapter. I added deploy scripts to the package.json. Here's what they look like...

```json
"predeploy": "npm run build",
"deploy": "aws s3 sync build/ s3://YOUR_S3_DEPLOY_BUCKET_NAME",
"postdeploy": "aws cloudfront create-invalidation --distribution-id YOUR_CF_DISTRIBUTION_ID --paths '/*' && aws cloudfront create-invalidation --distribution-id YOUR_WWW_CF_DISTRIBUTION_ID --paths '/*'"
```

Now, I can update my files and simply...

```
$ npm run deploy
```

**Comment by jayair** [comment]
@geirman right on! I'll remember to add this detail when I update things.

**Comment by jayair** [comment]
@geirman added your suggestion to the chapter febd147b52b8a94bb8a23b2ded62dda4b6813a07

**Comment by PatrykTies** [comment]
It gives me error for CloudFront, Invalid invalidation paths
I found a tip here : https://kylewbanks.com/blog/invalidate-entire-cloudfront-distribution-from-command-line
It works now, but so far I cannot see site updated...tried few time over few hours

**Comment by jayair** [comment]
@PatrykTies that is weird. Which OS are you on btw?

**Comment by PatrykTies** [comment]
Win7 Pro 64bit SP1

**Comment by jayair** [comment]
@PatrykTies Ah I'm not too familiar with the shell in Windows but maybe the escape `\` works differently there?

**Comment by PatrykTies** [comment]
Let me google it out and investigate. Cheers

**Comment by PatrykTies** [comment]
Btw using npm script also gives the same error....but that get injected into win shell anyways...so

**Comment by PatrykTies** [comment]
Solved, for win7 I had to use /^*  as --paths, instead of "/*"
Thanks for pointing the possible cause. All done
Now off me got to Jenkins and AWS codepipeline CI/CD  for this tut

**Comment by jayair** [comment]
@PatrykTies thanks for reporting back. I'm sure it'll help other folks.

Btw, let us know how your Jenkins setup works out, we are considering writing about that as well.

**Comment by ryanjcruz** [comment]
I'm getting an error on postdeploy:
`An error occurred (InvalidArgument) when calling the CreateInvalidation operation: Your request contains one or more invalid invalidation paths.`
`aws cloudfront create-invalidation --distribution-id CF_DISTRIBUTION_ID --paths '/*' && aws cloudfront create-invalidation --distribution-id WWW_CF_DISTRIBUTION_ID --paths '/*'`

But when executed individually, they both seem to work
`aws cloudfront create-invalidation --distribution-id CF_DISTRIBUTION_ID --paths '/*'`
`aws cloudfront create-invalidation --distribution-id WWW_CF_DISTRIBUTION_ID --paths '/*'`

**Comment by jayair** [comment]
@ryanjcruz Are you on Windows?

**Comment by ryanjcruz** [comment]
@jayair yep windows 10, but using git bash to run the command

**Comment by jayair** [comment]
@ryanjcruz I see. How do you combine two shell commands together?

**Comment by ryanjcruz** [comment]
@jayair see my package.json

https://github.com/ryanjcruz/notes-app-client/blob/master/package.json

**Comment by jayair** [comment]
@ryanjcruz Hmm. Isn't that the same as the source repo? - https://github.com/AnomalyInnovations/serverless-stack-demo-client/blob/master/package.json#L22

**Comment by ryanjcruz** [comment]
@jayair looks like it is, Maybe the syntax has some issues with non-unix like machine. I think the issue for windows is the `&&` part as running them individually seems to go just ok.

**Comment by ryanjcruz** [comment]
@jayair finally figured it out on another project, for windows `--paths '/*'` should be just `--paths /*`

**Comment by littleredshack** [comment]
Strange one.  I have got all the way through the process and all working fine.  But when I try to redeploy to S3 I get an error about my AWS key being invalid.  

C:\Users\gstokes\Documents\Personal\Coding\Serverless\notes-app-frontend\notes-app-client>aws s3 sync build/ s3://gbs-notes-app-client
fatal error: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.

I have re-run AWS configure just in case those got changed somehow.  Still not working.

Anyone got any ideas?

**Comment by littleredshack** [comment]
I just went into IAM and then in the user that I had originally created I chose the option to create a new Access Key.  I used that and it is working. No idea why the previous suddenly stopped.

**Comment by drakeloud** [comment]
I'm not sure if anyone else has pointed this out in a different chapter, but I think that you should add the --delete flag when syncing your s3 bucket. So the full command would be this:

aws s3 sync build/ s3://YOUR_S3_DEPLOY_BUCKET_NAME --delete

This deletes the files that aren't in your local directory. When you run npm build, it creates unique ids for the static files, so simply syncing s3 gives you the old files, and adds the new ones. E.g. my app is 6MB and it was adding another 6MB every time I deploy.

**Comment by jayair** [comment]
@drakeloud Good point. I'll add a note.

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-deploy-again/106

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-deploy-again/138
