### ISSUE TITLE
Great tutorial! Do you know how to populate more pages in a website?

### ISSUE THREAD

**Issue by BenHugh** [AnomalyInnovations/serverless-stack-com#79]
Instead of building a static website, I want to populate more pages automatically, but don't know how to make this happen since I want this to be a serverless application.

**Comment by jayair** [comment]
Are you talking about the frontend portion of the demo app that we are building in the tutorial?

**Comment by BenHugh** [comment]
Yes!  should I use some kind of framework and where should I put the code? Still in S3?

**Comment by jayair** [comment]
Well for our frontend portion we are using React as a static single page app. To clarify, do you want to use React but not as a static site?

**Comment by BenHugh** [comment]
I want to build a serverless website(not a static website) with multiple pages, and all the pages content should be populated automatically based on the url link clicked. I'm still new to serverless, not sure which framework I should use to make this happen,

**Comment by jayair** [comment]
Hmmm I'm not sure how the dynamic content you are looking for is different from the React.js app we create in the tutorial. But if you are looking for setting up something like Express to serve out dynamic content through AWS Lambda, there is this project - https://github.com/awslabs/aws-serverless-express

**Comment by jayair** [comment]
Closing this.
