### ISSUE TITLE
Comments: Who Is This Guide For?

### ISSUE THREAD

**Issue by jayair** [AnomalyInnovations/serverless-stack-com#8]
Link to chapter - http://serverless-stack.com/chapters/who-is-this-guide-for.html

**Comment by sreesarma** [comment]
Typo:

We are also catering this ~~soley~~ solely towards JavaScript developers for now.

**Comment by jayair** [comment]
@sreesarma good catch, thanks!

**Comment by jayair** [comment]
This issue was moved to https://discourse.serverless-stack.com/t/comments-who-is-this-guide-for/96
