### ISSUE TITLE
Can't Create Cognito Test User 

### ISSUE THREAD

**Issue by willybeans** [AnomalyInnovations/serverless-stack-com#82]
$ aws cognito-idp sign-up \
>   --region us-east-1 \
>   --client-id 5cj9ag4nvskjkv0dg3sade5fd5 \
>   --username admin@example.com \
>   --password Passw0rd! \
>   --user-attributes Name=email,Value=admin@example.com

An error occurred (ResourceNotFoundException) when calling the SignUp operation: User pool client 5cj9ag4nvskjkv0dg3sade5fd5 does not exist.

So ive check that the client id number is the number im getting from "app client id:" under user pools. Ive double checked that my aws configure credentials are correct with my IAM user keys and secret key. Im at a loss for why im getting this error. Any ideas? 

I'm running windows 10.

**Comment by jayair** [comment]
@willybeans one issue could be the region. Can you verify the region for your User Pool?

**Comment by willybeans** [comment]
@jayair 
I was entering us-east-1 but my pool is set to us-east-2. Although i'm not able to confirm this fixed it im fairly confident that it will work when i get home so im going to close. Thank you for the suggestion that didnt occur to me to check that. thank you thank you thank you!

**Comment by TrebuhD** [comment]
I'm having a similar problem while executing `cognito-idp admin-initiate-auth`. I verified that my pool and aws-cli are both set to the same region (eu-central-1), but I'm still getting `An error occurred (ResourceNotFoundException) when calling the AdminInitiateAuth operation: User pool eu-central-1_XXXXXXX does not exist`. Any ideas?

**Comment by toyeebgodo** [comment]
Changing the location to us-east-2 solved my problem.
