### ISSUE TITLE
Delete S3 object

### ISSUE THREAD

**Issue by vfonsecapv** [AnomalyInnovations/serverless-stack-com#89]
Hi guys, I update the project with S3 delete object, can I pull request?

**Comment by jayair** [comment]
Hi @vfonsecapv I had kinda worked on it myself as well. But if you've already made the changes then go ahead. I'll review it and merge it in.

**Comment by vfonsecapv** [comment]
Ok I will. Thanks!

**Comment by jayair** [comment]
Thanks for taking the time to put it together! I'll work on it soon.
