### ISSUE TITLE
Deploy the APIS

### ISSUE THREAD

**Issue by raiden357** [AnomalyInnovations/serverless-stack-com#96]
curl: (6) Couldn't resolve host 'ly55wbovq4.execute-api.us-east-2.amazonaws.com'

not sure what to do

**Comment by jayair** [comment]
Did it deploy successfully for you?

**Comment by raiden357** [comment]
yeah it did. I think i misunderstood this:

"Now we can use that as the Authorization header to make a request to our API (at the POST endpoint returned after running serverless deploy above) using the following:"

$ curl https://ly55wbovq4.execute-api.us-east-1.amazonaws.com/prod/notes \ etc........

I thought I had to execute that command, but I think it was saying the header would be used later

**Comment by jayair** [comment]
@raiden357 Yeah to make the curl request we need to pass in the `Authorization` header from the `aws cognito-idp admin-initiate-auth` command.

**Comment by raiden357** [comment]
thank you.
