### ISSUE TITLE
npm ERR! missing script: start

### ISSUE THREAD

**Issue by raiden357** [AnomalyInnovations/serverless-stack-com#97]
I keep getting this error. It happened when I deleted the favicon folder after extracting the favicon files and placing them in the public directory.

here is the package.json file:

```
{
  "name": "notes-app-api",
  "version": "1.0.0",
  "description": "",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "aws-sdk": "^2.67.0",
    "babel-core": "^6.25.0",
    "babel-loader": "^7.0.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "glob": "^7.1.2",
    "serverless-webpack": "^1.0.0-rc.4",
    "webpack": "^2.6.1",
    "webpack-node-externals": "^1.6.0"
  },
  "dependencies": {
    "babel-runtime": "^6.23.0",
    "react-bootstrap": "^0.31.0",
    "react-router-dom": "^4.1.1",
    "uuid": "^3.0.1"
  }
}
```

**Comment by jayair** [comment]
@raiden357 I think you might have messed up the two projects. The [backend](https://github.com/AnomalyInnovations/serverless-stack-demo-api) and [frontend](https://github.com/AnomalyInnovations/serverless-stack-demo-client) are two different projects.

When you start working on the frontend, create a new directory for it. So it'll have it's own `package.json`.

**Comment by raiden357** [comment]
thx
